### ISSUE TITLE
Wheels for python 3.10

### ISSUE THREAD

**Issue by JPfeP** [SpotlightKid/python-rtmidi#108]
Hello,

I would like to know if official support for Python 3.10 is on the way, and if binary wheels are planned as well ? Will it be possible then for you to provide a build for the new M1 arm architecture for Mac OS ?

Greetings,

JP

**Comment by SpotlightKid** [comment]
Yes, I plan a new release for in around the April 15th with official Python 3.10 support and binary wheels for Windows, `manylinux` and MacOS. I'll have to figure out how to do MacOS M1 builds, through.

**Comment by JPfeP** [comment]
Hi, 

I would like to know if there are any news about the planned release ? Is building for M1 still a challenge ?

Thx, 

JP

**Comment by SpotlightKid** [comment]
Sorry, family business got in the way, I'll try to get to next week.

**Comment by ElliotGarbus** [comment]
I'm looking forward to the update - but just really wanted to say thank you for creating & supporting this library.

**Comment by BlendThatFilm** [comment]
Is there any news on this being updated to Python 3.1, I use a Blender Addon by @JPfeP that is reliant on python-rtmidi and thus I can't move onto any newer versions of Blender.  I hate bothering developers but if you could let me know I'd really appreciate it.

**Comment by tparker24** [comment]
I just upgraded to python 3.10.5 (on Windows 10) and get errors trying to install pyton-rtmidi: 

--------------------------------------------------------
d:\work>pip install python-rtmidi
Collecting python-rtmidi
  Using cached python-rtmidi-1.4.9.tar.gz (251 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: python-rtmidi
  Building wheel for python-rtmidi (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
---------------------------------------------------------

Appreciate any help, thanks.

**Comment by brunoenten** [comment]
Hi @SpotlightKid, any way we can help you with the python 3.10 wheel?

**Comment by Bubobubobubobubo** [comment]
Hi, found myself in the same situation. Is there anything planned?

**Comment by acidcoolxxx** [comment]
**error: alsa/asoundlib.h: No such file or directory** this is what im getting. Guess we need to downgrade to a lower Version of python

**Comment by gitcaner** [comment]
I'm also trying to install rtmidi on python 3.10 and having issues.

**Comment by nikky78** [comment]
Has it been fixed yet? cause i'm facing the same issue

**Comment by brunoenten** [comment]
It has been fixed on my fork. @SpotlightKid would you consider passing the baton to another maintainer?
Alternatively, I could rename the package on my fork to publish on pypy, but that would arguably be messier.

**Comment by SpotlightKid** [comment]
> @SpotlightKid would you consider passing the baton to another maintainer?

Please see #137

**Comment by brunoenten** [comment]
Done!

**Comment by tparker24** [comment]
I'm just a simple user.  I tried "pip install python-rtmidi" but it still 
fails.  Am I supposed to use some other method?


Bruno Enten wrote on 5/21/2023 2:23 AM:

**Comment by SpotlightKid** [comment]
@tparker24 Until a new version is released, you'll have to install from a Git repository checkout.

See https://spotlightkid.github.io/python-rtmidi/install-windows.html#download-unpack-python-rtmidi-source and ignore the first paragraph in that section.

**Comment by tparker24** [comment]
Thanks.  I tried a bit, but this stuff is way above me.

I guess I'll just have to wait until a new version is released on pypi.

Thanks,
Tom

Christopher Arndt wrote on 5/21/2023 9:50 AM:
