### ISSUE TITLE
note iterable first argument

### ISSUE THREAD

**Issue by amirteymuri** [SpotlightKid/python-rtmidi#11]
In the examples there are note_on and note_off lists with the channel numbers like `0x90`. Why are there numbers (hex_numbers?) and not integer numbers?

**Comment by SpotlightKid** [comment]
It's just a different integer literal notation. It makes it easier to recognize the status byte and the midi channel. The midi command is determined by the higher nibble (4-bits) of the status byte, i.e. the first hexedecimal numeral and the midi channel by the lower nibble (second numeral). If you change the midi channel, only the second numeral changes, the first numeral stays the same, making it easy discern, whether you have e.g. a note on (0x9*n*) or a note off (0x8*n*).
