### ISSUE TITLE
[Question] Is there anyway to read .midi file content using python-rtmidi?

### ISSUE THREAD

**Issue by Nova-Noir** [SpotlightKid/python-rtmidi#122]
Hey, I searched for a while and didn't see the solution using python-rtmidi (maybe it's because I'm bad at searching)

What I want to do is to read .midi file's content and to get all of the events, notes or ticks, and then use midioutput to make something like autoplay.

Is there any possible way to do that using python-rtmidi?

**Comment by ElliotGarbus** [comment]
You might prefer a higher level construct that uses python-rtmidi as a back-end.  I like mido.  Read: https://mido.readthedocs.io/en/latest/

**Comment by Nova-Noir** [comment]
Yes, this is working, thank you!
