### ISSUE TITLE
incomplete message!

### ISSUE THREAD

**Issue by teymuri** [SpotlightKid/python-rtmidi#128]
Some times by playing around I get this user warning:

> UserWarning: MidiOutAlsa::sendMessage: incomplete message!

What is this warning saying?

**Comment by SpotlightKid** [comment]
To diagnose this, it would be help to know what you are sending or receiving when this message occurs.

**Comment by SpotlightKid** [comment]
No feedback in a reasonable timeframe → closing this.

If this is still an issue and you have more information, please feel free to re-open.

**Comment by SpotlightKid** [comment]
See my comment here on why the message in the above comment is not valid: https://github.com/SpotlightKid/python-rtmidi/issues/179#issuecomment-1725900186
