### ISSUE TITLE
can we save the midiout to a midi file?

### ISSUE THREAD

**Issue by Liujingxiu23** [SpotlightKid/python-rtmidi#130]
can we save the midiout to a midi file? something like midiout.save("temp.midi")

**Comment by SpotlightKid** [comment]
RtMidi and therefor `python-rtmidi` does not handle Standard MIDI File writing or reading. There are other libraries for that.

I have one too: https://github.com/SpotlightKid/miditk-smf

But it doesn't have much documentation nor is it very well tested in the field.
