### ISSUE TITLE
Send MIDI output with python-RtMidi

### ISSUE THREAD

**Issue by Beeeton** [SpotlightKid/python-rtmidi#132]
Good day people! I am looking for a way to use python to send MIDI messages to other programs that receive MIDI input. In other words, use my python program as a MIDI keyboard of some kind. What would be the proper way to do that?

**Comment by Beeeton** [comment]
Well i found a program that creates MIDI ports which i can use to transmit messages from Python to other program, and it pretty much works, but requires an additional program to work. I hope there is a way to create MIDI ports with Python

**Comment by SpotlightKid** [comment]
https://spotlightkid.github.io/python-rtmidi/rtmidi.html#rtmidi.MidiIn.open_virtual_port

Not supported by the Windows MMS API, though.
