### ISSUE TITLE
Using Python to read input of 2 keyboards

### ISSUE THREAD

**Issue by Beeeton** [SpotlightKid/python-rtmidi#133]
Good day People! I am looking for a way to use 2+ keyboards as individual devices in my program, and i can currently see 2 ways of making it work.
1) Making program be able to find all usb devices and then choose ONLY ONE device to read output from(ignore all other devices), and then just run N instances of program
2) Making program be able to find out from which device input is coming from(figure out keyboard on KeyPressed event) and then make next part of logic.
Does someone have any good ideas how to make either of these work?

**Comment by SpotlightKid** [comment]
You need to create a `MidiIn` instance for each device.

Or just use a MIDI framework, which allows to connect multiple devices to an input, like [JACK](https://jackaudio.org/), ALSA or CoreMIDI on macOS.

**Comment by Beeeton** [comment]
I've tried working with JACK but to no avail. Can you please elaborate both of the ideas you suggested. How do you create a MidiIn instance for a device? How do you use JACK to connect multiple devices to MIDI port, and how that differs them?

**Comment by SpotlightKid** [comment]
Sorry, I can't teach you how to use JACK. Please visit the FAQ on its [homepage](https://jackaudio.org) and maybe also https://wiki.archlinux.org/title/Professional_audio to learn more. Letting JACK/ALSA handle multiple devices is the easiest option on Linux, but in general also works on macOS and Windows, but is not as user-friendly there.

If this is not an option, you present the user with a list of detected MIDI input devices and then for each one, which the user chooses to use, you create an `rtmidi.MidiIn` instance and register an input callback (see API docs). In the callbacks you dispatch them to the appropriate parts of your app (for example, in a PyQt app using signals).
