### ISSUE TITLE
Using Python to get IdVendor and IdProduct of the device input just came from

### ISSUE THREAD

**Issue by Beeeton** [SpotlightKid/python-rtmidi#134]
I need to somehow differ 2 keyboard inputs, and the only way to do that seems to work is comparing their IdVendor and IdProduct values. I can get these for both keyboards, but i can't get these values during runtime(on KeyPressed event, for example). Any ideas how to do that?

**Comment by SpotlightKid** [comment]
Libusb?

I think this is out-of scope of python-rtmidi and maybe even RtMidi. Anyway, if at all, it should be implemented in the latter.
