### ISSUE TITLE
Cannot install python-rtmidi on Windows 10

### ISSUE THREAD

**Issue by superslonic** [SpotlightKid/python-rtmidi#135]
Hi! I've done everything that's written here: [https://spotlightkid.github.io/python-rtmidi/install-windows.html](https://spotlightkid.github.io/python-rtmidi/install-windows.html)

But I'm getting this:

```
(base) (rtmidi) PS C:\Users\hyperslonic\Desktop\python-rtmidi> python setup.py install
C:\Users\hyperslonic\Desktop\python-rtmidi\setup.py:27: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  JACK1_MIN_VERSION = StrictVersion('0.125.0')
C:\Users\hyperslonic\Desktop\python-rtmidi\setup.py:28: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  JACK2_MIN_VERSION = StrictVersion('1.9.11')
running install
C:\Users\hyperslonic\rtmidi\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Users\hyperslonic\rtmidi\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing python_rtmidi.egg-info\PKG-INFO
writing dependency_links to python_rtmidi.egg-info\dependency_links.txt
writing top-level names to python_rtmidi.egg-info\top_level.txt
reading manifest file 'python_rtmidi.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '.appveyor.yml'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching '*.rst.in'
no previously-included directories found matching 'ci'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
adding license file 'LICENSE.txt'
adding license file 'AUTHORS.rst'
writing manifest file 'python_rtmidi.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'rtmidi._rtmidi' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

**Comment by gitagogaming** [comment]
I am also receiving this error unfortunately and I do have Visual C++ 14 or greater

**Comment by SpotlightKid** [comment]
Which Python version (version number, arch, 32/64-bit?) do you have installed?

Unfortunately https://wiki.python.org/moin/WindowsCompilersis outdated and does not provide info on Python 3.11. I don't know which version of VC++ it requires.

**Comment by brunoenten** [comment]
@SpotlightKid could you update gh-pages settings to use the new markdown documentation?

**Comment by SpotlightKid** [comment]
@brunoenten You can update the gh-pages with the  `update-docs.sh` script. I did that now.

Is it that what you meant?

**Comment by brunoenten** [comment]
I thought this script was obsolete, sorry.
@superslonic could you check the updated documentation and try again?

You can also try installing directly the binary wheels with
` pip install python-rtmidi`

**Comment by brunoenten** [comment]
That's it, the 1.5.0 release with binary wheels for recent cpython has been released on pypi!
https://pypi.org/manage/project/python-rtmidi/release/1.5.0/

Please let me know if `pip install python-rtmidi` now works for you.

**Comment by SpotlightKid** [comment]
Closing this, since we received no further feedback and we provide working binary wheels for windows with release 1.5.1 and the build system has changed completely since this was openened.
