### ISSUE TITLE
feature request for midiconstants.py

### ISSUE THREAD

**Issue by wolkstein** [SpotlightKid/python-rtmidi#14]
Hi,
first of all many thx for this great python implantation of rtmidi!!

i have a small feature request to form an midi message using  midiconstants.

for example CC is defined as:
CONTROLLER_CHANGE = CONTROL_CHANGE = 0xB0
1011cccc 0ccccccc 0vvvvvvv (channel, controller, value)

Which mean if you form your midi message using this constants it look like this:
control = [CONTROLLER_CHANGE,  21,  127]

this will send an CC Event with Data1 = 21 and Data2 = 127 on MIdi Channel "1".

so it is only possible, if you use the midiconstants, to send on channel 1.

my feature request is to split MESSAGE Event kind from the Midi Channel that you can form an message like this.

control =  [ 8, CONTROLLER_CHANGE,  21,  127 ]
mean:
Midi Channel 8, CC Event Kind, Data 1 (21), Data 2 (127)
or:
0111   1011nnnn   0ccccccc   0vvvvvvv

in most examples here, which i read, i fond the explanation for the control message format like this:
 note_on = [NOTE_ON, 60, 112]  # channel 1, middle C, velocity 112  
i think to call the NOTE_ON Event kind "Channel1" can produce a misunderstanding.  people like me interpret the meaning of Channel as Midi Channel 1-16.

/g
wolke

**Comment by SpotlightKid** [comment]
(python-)RtMidi is very low-level. The `MidiOut.send_message`` method expects the MIDI bytes exactly as they go over the wire, which means the channel is encoded in the lower four bits of channel mode message status bytes. Since four bits can represent values from 0-15, the channel is zero-based, but the "logical" channel counting in the MIDI spec is one-based (i.e. from 1 - 16).

It's easy to write a wrapper for `MidiOut` that offers convenience methods for sending common midi messages and handles passing the MIDI channel more intuitively.

Here's a quick example:

```#!python
import time
import rtmidi
from rtmidi.midiconstants import *


class MidiOut(rtmidi.MidiOut):
    def __init__(self, *args, **kwargs):
        self.channel = kwargs.pop('ch', 1)
        super(MidiOut, self).__init__( *args, **kwargs)

    def channel_message(self, command, *data, ch=None):
        """Send a MIDI channel mode message."""
        command = (command & 0xf0) | ((ch if ch else self.channel) - 1 & 0xf)
        msg = [command] + [value & 0x7f for value in data]
        self.send_message(msg)

    def note_off(self, note, velocity=0, ch=None):
        """Send a 'Note Off' message."""
        self.channel_message(NOTE_OFF, note, velocity, ch=ch)

    def note_on(self, note, velocity=0, ch=None):
        """Send a 'Note Off' message."""
        self.channel_message(NOTE_OFF, note, velocity, ch=ch)

    def program_change(self, program, bank=None, msb=None, lsb=None, ch=None):
        """Send a 'Program Change' message."""
        self.channel_message(PROGRAM_CHANGE, program, ch=ch)


mout = MidiOut(ch=3)
mout.open_virtual_port()
input('Press key...')
mout.program_change(40)
mout.note_on(60)
time.sleep(1)
mout.note_off(60)
```

**Comment by wolkstein** [comment]
hi,
many thx for the example :). this is exact my helper function which i need here!

/g
wolke
