### ISSUE TITLE
Apple Silicon macOS wheel?

### ISSUE THREAD

**Issue by akx** [SpotlightKid/python-rtmidi#147]
Hi there,

Would it be possible to also publish an Apple Silicon wheel for macOS? There's currently just a `rtmidi-2.5.0-cp311-cp311-macosx_13_0_x86_64.whl`, which obviously doesn't work that well with an arm64 Python:

> ImportError: dlopen(.../rtmidi/_rtmidi.cpython-311-darwin.so, 0x0002): tried: '.../rtmidi/_rtmidi.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS.../rtmidi/_rtmidi.cpython-311-darwin.so' (no such file), '.../rtmidi/_rtmidi.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by brunoenten** [comment]
Hi,

You're in the wrong project :)
This is python-rtmidi, you want pyrtmidi. Yeah, it's confusing.

Here's the link to pyrtmidi: https://github.com/patrickkidd/pyrtmidi

**Comment by akx** [comment]
@brunoenten Oop, sorry! (I switched to Portmidi for now anyway, so all good...)
