### ISSUE TITLE
[macOS] incompatible binary wheels for architecture M1 / arm64

### ISSUE THREAD

**Issue by mxjacknelson** [SpotlightKid/python-rtmidi#149]
I am running macOS Ventura 13.3.1, Python 3.11.3

After installing via: pip3 install python-rtmidi

I get:

Python 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rtmidi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/rtmidi/__init__.py", line 4, in <module>
    from ._rtmidi import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/opt/homebrew/lib/python3.11/site-packages/rtmidi/_rtmidi.cpython-311-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.11/site-packages/rtmidi/_rtmidi.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/python3.11/site-packages/rtmidi/_rtmidi.cpython-311-darwin.so' (no such file), '/opt/homebrew/lib/python3.11/site-packages/rtmidi/_rtmidi.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by m-m-adams** [comment]
I've got the same issue and same error. It was definitely working a couple weeks ago

**Comment by devleaks** [comment]
Same here. Worked perfectly with 1.4.9, python 3.10. Does not with 1.5.0, python 3.11.

**Comment by SpotlightKid** [comment]
As long as we're trying to fix this and provide proper binary wheels for macOS ARM, you can always try building yourself from the source dist:

    pip install --upgrade --no-cache-dir --no-binary python-rtmidi python-rtmidi

**Comment by devleaks** [comment]
Yes. Thanks. Works for me on python 3.11.

**Comment by brunoenten** [comment]
The new release (1.5.2) contains separate builds for Intel and M1. Could you try installing from the binaries again?

**Comment by devleaks** [comment]
Hi. Thanks for looking into this. I just installed 1.5.2 and same thing:

`ImportError: dlopen(/opt/homebrew/Caskroom/miniforge/base/envs/cockpit/lib/python3.11/site-packages/rtmidi/_rtmidi.cpython-311-darwin.so, 0x0002): tried: '/opt/homebrew/lib/_rtmidi.cpython-311-darwin.so' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/cockpit/lib/python3.11/site-packages/rtmidi/_rtmidi.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Caskroom/miniforge/base/envs/cockpit/lib/python3.11/site-packages/rtmidi/_rtmidi.cpython-311-darwin.so' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/cockpit/lib/python3.11/site-packages/rtmidi/_rtmidi.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`

But recompiling locally works.
Pierre

**Comment by devleaks** [comment]
file /opt/homebrew/Caskroom/miniforge/base/envs/cockpit/lib/python3.11/site-packages/rtmidi/_rtmidi.cpython-311-darwin.so gets installed (and uninstalled) by python-rtmidi package.
I tried with no cache, without recompiling, and same issue. Si it appears that it rellay is the file /opt/homebrew/Caskroom/miniforge/base/envs/cockpit/lib/python3.11/site-packages/rtmidi/_rtmidi.cpython-311-darwin.so that is missing the arm64 code... (but I'm no specialist..)
P

**Comment by SpotlightKid** [comment]
Could someone on arm64 macOS please try the following:

    pip uninstall python-rmidi
    pip -vv install -U --no-cache-dir --log install.log python-rtmidi
    python -c 'import rtmidi; print(rtmidi._rtmidi.__file__); print(rtmidi.__version__)'

and post the (content of the) file `install.log` here?

**Comment by devleaks** [comment]
```
 % python -c 'import rtmidi; print(rtmidi._rtmidi.__file__); print(rtmidi.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cockpit/lib/python3.11/site-packages/rtmidi/__init__.py", line 4, in <module>
    from ._rtmidi import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/opt/homebrew/Caskroom/miniforge/base/envs/cockpit/lib/python3.11/site-packages/rtmidi/_rtmidi.cpython-311-darwin.so, 0x0002): tried: '/opt/homebrew/lib/_rtmidi.cpython-311-darwin.so' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/cockpit/lib/python3.11/site-packages/rtmidi/_rtmidi.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Caskroom/miniforge/base/envs/cockpit/lib/python3.11/site-packages/rtmidi/_rtmidi.cpython-311-darwin.so' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/cockpit/lib/python3.11/site-packages/rtmidi/_rtmidi.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
(cockpit) pierre@Mac-mini-de-Pierre cockpitdecks %

Install log is attached.
[install.log](https://github.com/SpotlightKid/python-rtmidi/files/11746563/install.log)
```

**Comment by SpotlightKid** [comment]
Ok, the new log confirms that pip install downloaded the correct wheel (`python_rtmidi-1.5.2-cp311-cp311-macosx_11_0_arm64.whl`), but it's apparently broken.

@brunoenten It seems that the arm64 macOS wheels still contain an x86_64 dll.

```
$ curl -O https://files.pythonhosted.org/packages/f0/cf/d0b2102c34a1d02fcc1f7f6ceb8bbea6353b1fd6323f4c22fa8e4bda06c3/python_rtmidi-1.5.2-cp311-cp311-macosx_11_0_arm64.whl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  127k  100  127k    0     0   538k      0 --:--:-- --:--:-- --:--:--  540k
$ unzip python_rtmidi-1.5.2-cp311-cp311-macosx_11_0_arm64.whl 
Archive:  python_rtmidi-1.5.2-cp311-cp311-macosx_11_0_arm64.whl
  inflating: rtmidi/version.py       
  inflating: rtmidi/midiconstants.py  
  inflating: rtmidi/__init__.py      
  inflating: rtmidi/midiutil.py      
  inflating: rtmidi/_rtmidi.cpython-311-darwin.so  
  inflating: python_rtmidi-1.5.2.dist-info/RECORD  
  inflating: python_rtmidi-1.5.2.dist-info/WHEEL  
  inflating: python_rtmidi-1.5.2.dist-info/METADATA  
$ file rtmidi/_rtmidi.cpython-311-darwin.so 
rtmidi/_rtmidi.cpython-311-darwin.so: Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK>
```

**Comment by SpotlightKid** [comment]
Could someone on Arm64 macOS test the python-rtmidi wheel in this artifact Zip archive from [a test build](https://github.com/SpotlightKid/python-rtmidi/actions/runs/5294088093)?

https://github.com/SpotlightKid/python-rtmidi/suites/13667820039/artifacts/754976748

This should contain a dynlib with the correct architecture.

**Comment by devleaks** [comment]
I'd love to help, how can I do that? What do I need to install?

**Comment by SpotlightKid** [comment]
@devleaks Download the file artifacts.zip from the link in the comment above yours, unpack the zip and install the .whl file in it with `pip -U install <file>`. If you already have pythonrtmidi installed, uninstall it beforehand with `pip uninstall python-rtmidi`. Then try `python -c 'import rtmidi; rtmidi.get_cimpiled_apis()`.

**Comment by SpotlightKid** [comment]
@devleaks Thanks for the confirmation, that's very helpful!

If it's not too much to ask, could you again test a new binary wheel for macOS M1 in this archive:

https://github.com/SpotlightKid/python-rtmidi/suites/13717769095/artifacts/758819208

Remember to again uninstall any existing `python-rtmidi` installation before the test.

**Comment by devleaks** [comment]
I don't know how to load from artifact.zip, so unzipped, and tested each file individually...

```
 % for f in *macosx*arm64.whl
for> do
for> pip install -U $f
for> done
ERROR: python_rtmidi-1.5.2-cp310-cp310-macosx_10_14_arm64.whl is not a supported wheel on this platform.
ERROR: python_rtmidi-1.5.2-cp311-cp311-macosx_10_14_arm64.whl is not a supported wheel on this platform.
ERROR: python_rtmidi-1.5.2-cp38-cp38-macosx_10_14_arm64.whl is not a supported wheel on this platform.
ERROR: python_rtmidi-1.5.2-cp39-cp39-macosx_10_14_arm64.whl is not a supported wheel on this platform.
%
```

The installation of the previous artifact (python_rtmidi-1.5.2-cp311-cp311-macosx_11_0_arm64.whl) was working though.

I have MacOS 13.4 (Ventura), python 3.11.3, arm64 of course.
P.

**Comment by SpotlightKid** [comment]
> I don't know how to load from artifact.zip, so unzipped,

Yes, that was correct, see my instructions in the [comment above](https://github.com/SpotlightKid/python-rtmidi/issues/149#issuecomment-1596277487).

> The installation of the previous artifact (python_rtmidi-1.5.2-cp311-cp311-macosx_11_0_arm64.whl) was working though.

By that you mean you uninstalled any existing `python-rtmidi` version, installed the wheel and ran `python -c 'import rtmidi; print(rtmidi.get_compiled_apis()); mo = rtmidi.MidiOut(); print(mo.get_ports())'` and it reported the list of compiled APIs a `[1]` the list of available MIDI output ports?

**Comment by devleaks** [comment]
Yes, there was no python-rtmidi package in my pip list, I tried the four above wheels and you read the result for each one of them.
In doubt, I tried the previous wheel you sent me, and in that case pip installed it without problem.
Yes, the test command (python -c 'import rtmidi; print(rtmidi.get_compiled_api()); mo = rtmidi.MidiOut(); print(mo.get_ports())') lists all my midi devices.

Since all wheels were presents in the latest artifact, I was wondering which instruction I should use to let pip choose the most appropritate wheel for my setup. But then I tried to install each (macosx, arm64) wheel that was there and you read the result.

P.

**Comment by SpotlightKid** [comment]
Ok, thanks. You guessed correctly that you have to tell pip which wheel file to use. Automatic selection only works when installing from PyPI (without further special options).

**Comment by bigredfrog** [comment]
Although I cannot test this myself, we have hit this issue in the ledfx project, I appreciate the prior help in resolving for windows, will see what we can stir up in this case...

**Comment by YeonV** [comment]
<img width="1168" alt="image" src="https://github.com/SpotlightKid/python-rtmidi/assets/28861537/36a58a0c-7ed4-44e9-83c2-04e4471f7d36">

**Comment by SpotlightKid** [comment]
@bigredfrog I seems you tried to install the wheel from the previous artifact.zip, the one that @devleaks already tested.

Please use the artifact.zip from [this comment](https://github.com/SpotlightKid/python-rtmidi/issues/149#issuecomment-1599175069) and use the file `python_rtmidi-1.5.2-cp311-cp311-macosx_11_0_arm64.whl`  in it for testing.

**Comment by bigredfrog** [comment]
@YeonV see above, noting that YeonV is the test hero here! I have no Mac...

**Comment by SpotlightKid** [comment]
Sorry, mixed up the mentions.

**Comment by YeonV** [comment]
> ~@bigredfrog~ @YeonV It seems you tried to install the wheel from the previous `artifact.zip`, the one that @devleaks already tested. We already know that this doesn't work.
> 
> Please use the new `artifact.zip` from [this comment](https://github.com/SpotlightKid/python-rtmidi/issues/149#issuecomment-1599175069) and use the file `python_rtmidi-1.5.2-cp311-cp311-macosx_11_0_arm64.whl` in it for testing.

omg sry.
tried the new one. it WORKS :)

**Comment by devleaks** [comment]
Was away this morning.
From https://github.com/SpotlightKid/python-rtmidi/suites/13737736851/artifacts/760404820
wheel python_rtmidi-1.5.2-cp311-cp311-macosx_11_0_arm64.whl works perfectly as expected (on my system, of course).
Pierre

**Comment by SpotlightKid** [comment]
Release 1.5.3 is out now:

https://github.com/SpotlightKid/python-rtmidi/releases/tag/1.5.3

Please test.

**Comment by YeonV** [comment]
> 

Works great!! thank you very much!!!

**Comment by devleaks** [comment]
Works for me too. Thank you all.
Best regards.
P.
