### ISSUE TITLE
midi2command.py : @lru_cache() error in Python 2.7.9

### ISSUE THREAD

**Issue by pacificweb** [SpotlightKid/python-rtmidi#15]
Hi SpotlightKid !

I have an error with the midi2command script

Line 123 : @lru_cache()
TypeError: < lambda > () takes exactly 1 argument (0 given)

Should I remove the lru_cache code or what can I do ?

There is no urge !

**Comment by SpotlightKid** [comment]
You got me there, obviously I didn't test this script with Python < 3.2!

On line 38 I was trying to substitute a no-op lambda function for the `lru_cache` decorator, which isn't present in earlier versions of Python, but I overlooked that  `lru_cache` is a function that *returns* a decorator (see [the docs here](https://docs.python.org/3/library/functools.html#functools.lru_cache)).

Here are two quick workarounds (choose one):

a) Install [backports.functools_lru_cache](https://pypi.python.org/pypi/backports.functools_lru_cache/1.3) and change line 38 to:

    from backports.functools_lru_cache import lru_cache

b) Change line 38 to:

    lru_cache = lambda: lambda func: func

Not using `lru_cache` will have a slight perform impactm but only if you have a *very large* config file.

I'll correct that in the next release.

**Comment by pacificweb** [comment]
Thanks !

Will go with the B) solution and it works;

On the Raspberry PI 2 (Raspbian) I am unable to install backports.functools_lru_cache

_pi@raspberrypi /tmp/lru/backports.functools_lru_cache $ pip install backports-functools-lru-cache
Downloading/unpacking backports-functools-lru-cache
Could not find any downloads that satisfy the requirement backports-functools-lru-cache
Cleaning up...
No distributions at all found for backports-functools-lru-cache
Storing debug log for failure in /home/pi/.pip/pip.log_

**Comment by SpotlightKid** [comment]
You need to get the name of the package right. Its "backports.functools_lru_cache" not "backports-functools-lru-cache" (notice the dot and the underscores).

**Comment by SpotlightKid** [comment]
Fixed in 18572fb3dc636dfe9218df2cc374f805bcc0ff77.
