### ISSUE TITLE
Using internal sound device on mac

### ISSUE THREAD

**Issue by gkvoelkl** [SpotlightKid/python-rtmidi#17]
Hi,

You did a great job.

How is it possible to use internal sound device on mac?

Best regards 

Gerhard

**Comment by SpotlightKid** [comment]
You mean, how to generate sound output with python-rtmidi on OS X?

python-midi only sends MIDI messages and they do not make sounds by themselves, they only tell a MIDI receiver what to play etc. So you need a synthesizer to turn the MIDI commands into sound. AFAIK, OS X does not have a builtin MIDI synthesizer like Windows does (nor does Linux, btw).  So you need to install one. An example would be a soundfont player like fluidsynth resp. Qsynth (GUI for fluidsynth). See this page for more information:

https://github.com/wbsoft/frescobaldi/wiki/MIDI-playback-on-Mac-OS-X

After you start Qsynth, you should be able to see its MIDi input port with `MidiIn.get_ports()`. Then open the port and just start sending MIDI messages to it. See the example scripts in the `examples/basic` directory.

**Comment by gkvoelkl** [comment]
Hi,

I will try this.

Best regards Gerhard
