### ISSUE TITLE
Error when installing on Raspberry PI (1.5.5)

### ISSUE THREAD

**Issue by darkroasted** [SpotlightKid/python-rtmidi#176]
First thanks for your great project! 

However when I try to install 1.5.5 using pip on my raspberry pi for LedFX then the install fails and provides the following output. Installing version 1.5.2 does not fail. How can i solve this?

Output:
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      + meson setup /tmp/pip-install-xrnqqcws/python-rtmidi_2b76ce7b0c8149c3ae95fe46f87c31bd /tmp/pip-install-xrnqqcws/python-rtmidi_2b76ce7b0c8149c3ae95fe46f87c31bd/.mesonpy-6skv9tq0 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dwheel=true -Dverbose=false -Dbuildtype=plain --native-file=/tmp/pip-install-xrnqqcws/python-rtmidi_2b76ce7b0c8149c3ae95fe46f87c31bd/.mesonpy-6skv9tq0/meson-python-native-file.ini
      The Meson build system
      Version: 1.2.1
      Source dir: /tmp/pip-install-xrnqqcws/python-rtmidi_2b76ce7b0c8149c3ae95fe46f87c31bd
      Build dir: /tmp/pip-install-xrnqqcws/python-rtmidi_2b76ce7b0c8149c3ae95fe46f87c31bd/.mesonpy-6skv9tq0
      Build type: native build
      Project name: python-rtmidi
      Project version: 1.5.5
      C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110")
      C++ linker for the host machine: c++ ld.bfd 2.35.2
      Host machine cpu family: arm
      Host machine cpu: arm
      Found pkg-config: /usr/bin/pkg-config (0.29.2)
      Dependency jack found: NO found 0.125.0rc1 but need: '>=1.9.11'
      Found CMake: /usr/bin/cmake (3.18.4)
      Run-time dependency jack found: NO (tried pkgconfig and cmake)
      Run-time dependency jack found: YES 0.125.0rc1
      Run-time dependency alsa found: YES 1.2.4
      Run-time dependency threads found: YES
      Has header "semaphore.h" : YES
      Program python3 found: YES (/usr/bin/python3)
      Program cython found: YES (/tmp/pip-build-env-4tuqnt43/overlay/bin/cython)
      Run-time dependency python found: YES 3.9
      Configuring version.py using configuration
      Build targets in project: 1
python-rtmidi 1.5.5

        Configuration
          Host machine system     : linux
          Python version          : 3.9
          Debug messages (verbose): False
          Build for wheel         : True
          JACK support            : True
          ALSA support            : True
          CoreMIDI support        : False
          Window MM support       : False

        User defined options
          Native files            : /tmp/pip-install-xrnqqcws/python-rtmidi_2b76ce7b0c8149c3ae95fe46f87c31bd/.mesonpy-6skv9tq0/meson-python-native-file.ini
          buildtype               : plain
          b_ndebug                : if-release
          b_vscrt                 : md
          verbose                 : false
          wheel                   : true

      Found ninja-1.11.1.git.kitware.jobserver-1 at /tmp/pip-build-env-4tuqnt43/overlay/bin/ninja

      meson-python: error: Required "project.version" field is missing and not declared as dynamic
      [end of output]

**Comment by SpotlightKid** [comment]
Thanks for the report!

The build backend changed from `mesonpep517` to `meson-python` in version 1.5.3.

Unfortunately `meson-python` 0.14.0, which in your case apparently was downloaded & used in the build process, changed how it handles the project version in `pyproject.toml`:

https://meson-python.readthedocs.io/en/latest/changelog.html#id1

> when `pyproject.toml` does not contain a `version` field and `version` is not declared 
> dynamic, raise an error instead of silently using the version declared in `meson.build`.

This means we have to add `dynamic = ['version']` to `pyproject.toml` now, when using `meson-python` >= 0.14.0.

I'll fix this and make a new 1.5.6 release asap. In the meantime, you can continue to use version 1.5.2. The actual library code hasn't changed.

**Comment by darkroasted** [comment]
Awesome! Thanks for your speedy reply and help!

I'll be looking forward to the merge and the 1.5.6 packet!
