### ISSUE TITLE
get_ports() returns garbled text on multi-byte character port name.

### ISSUE THREAD

**Issue by nai-kon** [SpotlightKid/python-rtmidi#180]
Hello.
If midi port name contains multi-byte characters, Japanese in my case, get_ports() returns garbled text.
Here is samples with multi-byte character "日本語" with means "Japanese".

## On Windows 10, python-rtmidi 1.5.6,  Python 3.11.5 

original port name
 ![image](https://github.com/SpotlightKid/python-rtmidi/assets/25865392/c6108336-90ab-448d-a5a8-804c6207cac4)

result
```python
>>>  import rtmidi
>>> rtmidi.MidiOut().get_ports()
['Microsoft GS Wavetable Synth 0', 'loopMIDI Port 1', 'loopMIDI Port æ\x97¥æ\x9c¬èª\x9e 2']
```

## On MacOS Sonoma on M1 Mac, python-rtmidi 1.5.6,  Python 3.11.5 

original port name
![image](https://github.com/SpotlightKid/python-rtmidi/assets/25865392/26fd0ebd-640f-4f60-9c32-31a22d451420)

result
```python
>>>  import rtmidi
>>> rtmidi.MidiOut().get_ports()
['IACdriver port with english', 'IACdriver port with Êó•Êú¨Ë™û']
```

Thanks.

**Comment by SpotlightKid** [comment]
You probably need to pass the correct encoding name to the `get_port()` method with the `encoding` keyword argument:

https://spotlightkid.github.io/python-rtmidi/rtmidi.html#rtmidi.MidiIn.get_ports

Or pass `None` as the encoding and get raw byte strings back.

**Comment by nai-kon** [comment]
`get_ports("utf-8")` returned a correct port name. Thank you!
