### ISSUE TITLE
Missing wheel for Python 3.12

### ISSUE THREAD

**Issue by luctrott** [SpotlightKid/python-rtmidi#181]
When I run `pip3.12 install python-rtmidi` on Windows, a prebuild wheel is not found and it tries to build the wheel locally, but fails because I don't have the necessary tools installed.
So could you please add a wheel for Python 3.12?

Thanks

**Comment by SpotlightKid** [comment]
Fixed in #182.

New release coming soon.

**Comment by SpotlightKid** [comment]
Release 1.5.7 is out:

https://github.com/SpotlightKid/python-rtmidi/releases/tag/1.5.7
