### ISSUE TITLE
import error on OSX 10.9 Symbol not found: _jack_activate

### ISSUE THREAD

**Issue by badgeek** [SpotlightKid/python-rtmidi#19]
here is the error message, i installed the library with

pip install python-rtmidi

and tried to compile from source using --no-jack parameter but still have the same error

any solutions?

thanks

```
>>> import rtmidi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xcorex/.pyenv/versions/3.5.2/lib/python3.5/site-packages/python_rtmidi-1.0.0-py3.5-macosx-10.9-x86_64.egg/rtmidi/__init__.py", line 4, in <module>
    from ._rtmidi import *  # noqa
ImportError: dlopen(/Users/xcorex/.pyenv/versions/3.5.2/lib/python3.5/site-packages/python_rtmidi-1.0.0-py3.5-macosx-10.9-x86_64.egg/rtmidi/_rtmidi.cpython-35m-darwin.so, 2): Symbol not found: _jack_activate
  Referenced from: /Users/xcorex/.pyenv/versions/3.5.2/lib/python3.5/site-packages/python_rtmidi-1.0.0-py3.5-macosx-10.9-x86_64.egg/rtmidi/_rtmidi.cpython-35m-darwin.so
  Expected in: flat namespace
 in /Users/xcorex/.pyenv/versions/3.5.2/lib/python3.5/site-packages/python_rtmidi-1.0.0-py3.5-macosx-10.9-x86_64.egg/rtmidi/_rtmidi.cpython-35m-darwin.so
```

**Comment by SpotlightKid** [comment]
Are you sure, re-compilation with `--no-jack` was successful and you really tested the resulting library? The error message indicates that `_rtmidi.cpython-35m-darwin.so` still references the jack library.

To make sure your build is fresh, please run `make clean` followed by `python setup.py build --no-jack` (this also deletes the `src/_rtmidi.cpp` file, so you'll need to have Cython installed).

**Comment by badgeek** [comment]
you are right, i need to cleanup the build first, it is working now, thanks!
