### ISSUE TITLE
pypi link to source code

### ISSUE THREAD

**Issue by micsthepick** [SpotlightKid/python-rtmidi#191]
![image](https://github.com/SpotlightKid/python-rtmidi/assets/11528421/210948c5-660a-405e-81bf-ed73e92edab1)
the pypi package points to the above (private or nonexistant) repository. (https://gitlab.com/SpotlightKid/python-rtmidi/)

**Comment by SpotlightKid** [comment]
@micsthepick Thanks for the heads up!
