### ISSUE TITLE
Cannot install on Bash on Windows Subsystem

### ISSUE THREAD

**Issue by Fleker** [SpotlightKid/python-rtmidi#2]
I set up Bash on Windows with the latest update in order to use rtmidi through a Linux command line without having to dual boot or use VMs. 

Though I installed the Linux libraries mentioned in the Wiki, I am running into an odd problem trying to install this library specifically. Bash on Windows is emulating Ubuntu 14.04 LTE.

Any feedback you have on how to get this working would be appreciated. Thanks.

    root@localhost:/etc/apt# sudo pip install rtmidi
    Downloading/unpacking rtmidi
     Downloading rtmidi-2.0.tar.gz
     Running setup.py (path:/tmp/pip_build_root/rtmidi/setup.py) egg_info for package rtmidi
    /usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'author', 'author_email', 'classifiers', 'description', 'keywords', 'url'
      warnings.warn(msg)

    Installing collected packages: rtmidi
    Running setup.py install for rtmidi
     /usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'author', 'author_email', 'classifiers', 'description', 'keywords', 'url'
      warnings.warn(msg)
     building 'rtmidi._rtmidi' extension
     x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -D__LINUX_ALSASEQ__= -I/usr/include/python2.7 -c RtMidi.cpp -o build/temp.linux-x86_64-2.7/RtMidi.o
     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
     RtMidi.cpp:39:20: fatal error: RtMidi.h: No such file or directory
      #include "RtMidi.h"
                         ^
     compilation terminated.
     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
     Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/rtmidi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-TLzE00-record/install-record.txt --single-version-externally-managed --compile:
     /usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'author', 'author_email', 'classifiers', 'description', 'keywords', 'url'

    warnings.warn(msg)

    running install

    running build

    running build_py

    creating build

    creating build/lib.linux-x86_64-2.7

     creating build/lib.linux-x86_64-2.7/rtmidi

    copying rtmidi/__init__.py -> build/lib.linux-x86_64-2.7/rtmidi

    copying rtmidi/collector.py -> build/lib.linux-x86_64-2.7/rtmidi

    copying rtmidi/randomout.py -> build/lib.linux-x86_64-2.7/rtmidi

    running build_ext

    building 'rtmidi._rtmidi' extension

    creating build/temp.linux-x86_64-2.7

    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -D__LINUX_ALSASEQ__= -I/usr/include/python2.7 -c RtMidi.cpp -o build/temp.linux-x86_64-2.7/RtMidi.o

    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]

    RtMidi.cpp:39:20: fatal error: RtMidi.h: No such file or directory

    #include "RtMidi.h"

                    ^

    compilation terminated.

    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

     ----------------------------------------
    Cleaning up...
    Command /usr/bin/python -c "import setuptools,     tokenize;__file__='/tmp/pip_build_root/rtmidi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-TLzE00-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/rtmidi
    Traceback (most recent call last):
      File "/usr/bin/pip", line 9, in <module>
      load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
     File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
      return command.main(cmd_args)
      File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
        text = '\n'.join(complete_log)
     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)

**Comment by SpotlightKid** [comment]
This seems like setuptools isn't working properly on Python under Windows-Ubuntu compatibility layer. The error messages do not make sense to me, when trying to match them to the contents of the `setup.py` file.

Also, the last error seems to be related to a problems pip had with `setup.py` files, which have non-ascii chars, even if it has the correct encoding declaration. This bug was fixed in later pip installations.

I recommend that you try to update setuptools and pip to the latest versions first and then try again.

**Comment by Fleker** [comment]
Thanks for getting back to me. I'll try doing that. This Linux emulation is very barebones. It seems like there's a lot of stuff I need to install before it can be usable.

**Comment by Fleker** [comment]
I got rtmidi to finally download. I'll do a PR with my instructions.

**Comment by SpotlightKid** [comment]
Yes, please do.

**Comment by SpotlightKid** [comment]
The above mentioned PR was #3, but instead of merging it I chose to put the provided information [in the wiki](https://github.com/SpotlightKid/python-rtmidi/wiki/User-contributed-documentation#installing-python-rtmidi-through-bash-on-windows).
