### ISSUE TITLE
MIDI port crashes if midi sent inside async socket server

### ISSUE THREAD

**Issue by EdwardDeaver** [SpotlightKid/python-rtmidi#201]
The package is closing or I'm guessing silently crashing when combined with async/threaded codebases:
The midi port goes away when viewed from other applications like Max. 

OS: MAC OS 14.0
DEVICE: MAC BOOK AIR M2 
PYTHON VERSION: 3.10.6
SHELL: ZSH

```
#!/usr/bin/env python

import asyncio
import websockets
from websockets.server import serve
import rtmidi
import time
import rtmidi

midiout = rtmidi.MidiOut()
available_ports = midiout.get_ports()
print(available_ports)
midiout.open_virtual_port("My virtual output")

# At this point "My virtual output" exists. 

async def handler(websocket):
    while True:
        number = 0
        try:
            message = await websocket.recv()
            with midiout:
            # At this point "My virtual output" IS GONE. 

                note_on = [0x90, number, 112] # channel 1, middle C, velocity 112
                note_off = [0x80, 60, 0]
                midiout.send_message(note_on)
                #time.sleep(0.5)
                midiout.send_message(note_off)
                #time.sleep(0.1)
                number = number +1
                available_ports = midiout.get_ports()
                print(available_ports)
        except websockets.ConnectionClosedOK:
            break
        print(message)

async def main():
    async with serve(handler, "localhost", 8765):
        await asyncio.Future()  # run forever

asyncio.run(main())
```

**Comment by SpotlightKid** [comment]
You can't use `with` with `MidiIn` / `MidiOut` instances the way you do it here in a loop. At the end of the `with`-clause the MIDI port [gets closed}(https://github.com/SpotlightKid/python-rtmidi/blob/master/src/_rtmidi.pyx#L470). That's actually exactly what the context manager is for.

**Comment by EdwardDeaver** [comment]
So to continuously send new midi notes you wouldn't use the "with midiout" statement? 

Or I guess how would you send new notes continuously?

**Comment by SpotlightKid** [comment]
yes, just leave out the  `with` statement and close the midi port if and when the async `handler` function returns (not yields).

**Comment by EdwardDeaver** [comment]
Awesome, thank you!
