### ISSUE TITLE
Unexpected Duplicate MIDI Messages in midiin_callback.py

### ISSUE THREAD

**Issue by jh2srv** [SpotlightKid/python-rtmidi#209]
### Issue: Unexpected Duplicate MIDI Messages in `midiin_callback.py`

**Description:**
When running the `midiin_callback.py` example with my MPKmini2, I’m experiencing repeated MIDI messages that do not reflect what I’m actually playing. Specifically, I see duplicate note-off messages and note-on messages.

**Steps to Reproduce:**
1. Connect an MPKmini2 MIDI device.
2. Run the `midiin_callback.py` example provided in this repository.
3. Play a simple chord on the device (i.e., press multiple notes simultaneously).
4. Observe the output in the console.

**Observed Output:**
Below is a sample of the output when playing a notes 60, 62, 64, 65, 67, 69:
```
[MPKmini2:MPKmini2 MIDI 1 16:0] @1730830919.305633 [144, 67, 79]
[MPKmini2:MPKmini2 MIDI 1 16:0] @1730830919.306825 [144, 62, 82]
[MPKmini2:MPKmini2 MIDI 1 16:0] @1730830919.306840 [144, 64, 78]
[MPKmini2:MPKmini2 MIDI 1 16:0] @1730830919.306844 [144, 69, 84]
[MPKmini2:MPKmini2 MIDI 1 16:0] @1730830919.306847 [144, 62, 82]
[MPKmini2:MPKmini2 MIDI 1 16:0] @1730830919.307865 [144, 60, 77]
[MPKmini2:MPKmini2 MIDI 1 16:0] @1730830919.400439 [128, 62, 0]
[MPKmini2:MPKmini2 MIDI 1 16:0] @1730830919.402669 [128, 60, 0]
[MPKmini2:MPKmini2 MIDI 1 16:0] @1730830919.408189 [128, 64, 0]
[MPKmini2:MPKmini2 MIDI 1 16:0] @1730830919.409687 [128, 69, 0]
[MPKmini2:MPKmini2 MIDI 1 16:0] @1730830919.409700 [128, 69, 0]
[MPKmini2:MPKmini2 MIDI 1 16:0] @1730830919.413606 [128, 67, 0]
```
For message 144 (note on), the note 65 is missing and note 62 repeated.
For message 128 (note off), the note 65 is missing and note 69 is repeated.

**Additional Details:**
- **Device:** MPKmini2
- **Environment:**
  - **Python Version:** 3.11.2
  - **python-rtmidi Version:** 1.5.8
  - **Hardware:** Raspberry Pi Zero
  - **OS:** Raspbian GNU/Linux 12 (Bookworm)
-  I can not reproduce the behavior under Windows 10, using the same midi controller.

**Comment by SpotlightKid** [comment]
Have you compared the MIDI input with what `aseqdump` reports?

Also, where is note 65? maybe you have enabled some kind of "force scale" mode on the MPK?

**Comment by jh2srv** [comment]
Thanks for your comment. I tried with aseqdump, I got similar results :

```
 16:0   Note on                 0, note 67, velocity 62
 16:0   Note on                 0, note 67, velocity 62
 16:0   Note on                 0, note 65, velocity 71
 16:0   Note on                 0, note 64, velocity 70
 16:0   Note on                 0, note 62, velocity 79
 16:0   Note on                 0, note 60, velocity 74
 16:0   Note off                0, note 62, velocity 0
 16:0   Note off                0, note 60, velocity 0
 16:0   Note off                0, note 64, velocity 0
 16:0   Note off                0, note 67, velocity 0
 16:0   Note off                0, note 65, velocity 0
 16:0   Note off                0, note 67, velocity 0
```

Note 67 is repeated, I was also playing the note 69 and it is missing (replaced in some way by note 67)
The MPKmini2 is connected directly to the Raspi Zero over USB. There is also no kind of special mode enabled with the MPKmini2.

So, we can say it is not related to rtmidi or python-rtmidi.
Even though is not related to rtmidi, do you have any ideas to solve the issue?

Thanks

**Comment by SpotlightKid** [comment]
Just the usual:

* Try a different USB cable
* Try a different USB port (though the zero probably hasn't got one, has it?)
* Try a different ALSA version.
* Try a different Raspi distro.

**Comment by jh2srv** [comment]
Thanks for the help
