### ISSUE TITLE
Jack API not recognized on Linux running Pipewire

### ISSUE THREAD

**Issue by imwihfm** [SpotlightKid/python-rtmidi#210]
Hi,

specifying the Jack-API causes the following error. I am using the Pipewire on Lubuntu:

```
$ pactl info | grep "Server Name"
Server Name: PulseAudio (on PipeWire 1.0.5)
```
So the Pipewire Jack proxy is not being recognized, and the following code throws the following error:
```
import time
import rtmidi


midiout = rtmidi.MidiOut(rtapi=rtmidi.get_compiled_api_by_name("jack"))
available_ports = midiout.get_ports()

if available_ports:
    midiout.open_port(0)
else:
    midiout.open_virtual_port("My virtual output")

with midiout:
    note_on = [0x90, 60, 112] # channel 1, middle C, velocity 112
    note_off = [0x80, 60, 0]
    midiout.send_message(note_on)
    time.sleep(0.5)
    midiout.send_message(note_off)
    time.sleep(0.1)

del midiout
```

The error:

```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Traceback (most recent call last):
  File "_rtmidi.pyx", line 1014, in _rtmidi.MidiOut.__cinit__
RuntimeError: MidiOutJack::initialize: JACK server not running?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/x.py", line 5, in <module>
    midiout = rtmidi.MidiOut(rtapi=rtmidi.get_compiled_api_by_name("jack"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_rtmidi.pyx", line 1016, in _rtmidi.MidiOut.__cinit__
_rtmidi.SystemError: MidiOutJack::initialize: JACK server not running?

shell returned 1
```
How could I tell rtmidi about using Pipewire, is this a new API?

**Comment by SpotlightKid** [comment]
There is no special API for Pipewire.

- Did you install JACK support for Pipewire (package `pipewire-jack`, I think)?
- Can you run other JACK clients successfully? E.g. try `jack_lsp`.

**Comment by imwihfm** [comment]
Yes, I can run other Jack-clients (jack_lsp, jack-keyboard etc) and the connections work fine. But with the above code, I'm not able to initialize the `MidiOut` instance `API_UNIX_JACK`.

**Comment by SpotlightKid** [comment]
Can you try starting the script via [pw-jack](https://man.archlinux.org/man/pw-jack.1)?

**Comment by imwihfm** [comment]
> Can you try starting the script via [pw-jack](https://man.archlinux.org/man/pw-jack.1)?

Output:
```
SystemError: MidiOutJack::initialize: JACK server not running?
```

**Comment by SpotlightKid** [comment]
Sorry, if I have to ask again: you have installed `pipewire-jack`?

And did you (resp. `pip`) build python-rtmidi yourself or did you download a binary wheel from PyPI?

**Comment by imwihfm** [comment]
Yes pipewire-jack is already installed on my Lubuntu.
I installed python-rtmidi from Pypi using `pip`.

**Comment by SpotlightKid** [comment]
Sorry, I'm not really sure what's going on.

Maybe you can try building `python-rtmidi` yourself on your system?

https://spotlightkid.github.io/python-rtmidi/installation.html#from-source

**Comment by imwihfm** [comment]
Hi, I uninstalled the pip-installed version and built it manually and the problems are gone! :+1:
