### ISSUE TITLE
No sound when using sfizz

### ISSUE THREAD

**Issue by flixman** [SpotlightKid/python-rtmidi#211]
I am trying to reproduce midi through sfizz, and I am not getting any sound at all. Maybe somebody can give a hand debugging this (I do not know if this related to sfizz or rtmidi). I am starting sfizz with this command:
```
sfizz_jack --jack_autoconnect true SalamanderGrandPianoV3_44.1khz16bit/SalamanderGrandPianoV3.sfz
```
When looking in qpwgraph I see the following:
![image](https://github.com/user-attachments/assets/1ce8d139-d1df-4795-87dd-ea2e3ff1dea2)
So  I guess this is ok. Then, I have wrapped the calls to rtmidi to this:

in my main.py
```python
    with MidiSynthSfizz('Client-128:qpwgraph_alsamidi 128:0') as synth:
        synth.play_buffer(events)
```

The MidSynthSfizz class is defined as:
```python
class MidiSynthSfizz(MidiSynth):
    def __init__(self, port: str = None):
        self.midi_out = rtmidi.MidiOut()
        available_ports = self.midi_out.get_ports()
        try:
            port_no = next(i for i,x in enumerate(available_ports) if x == port)
        except StopIteration:
            logger.info("Available MIDI ports:")
            for x in available_ports:
                logger.info("  %s", x)
            raise ValueError(f"Could not find port number for device {port}")

        self.midi_out.open_port(port_no)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        pass

    def play_buffer(self, buffer: list[MidiEvent]):
        while True:
            for i in range(len(buffer)):
                event = buffer[i]
                # play the event
                if isinstance(event, KeyChange):
                    if event.type == EventType.KEY_ON:
                        self.midi_out.send_message([0x90 + event.channel, event.key_no, event.velocity])
                    else:
                        self.midi_out.send_message([0x80 + event.channel, event.key_no, event.velocity])
                elif isinstance(event, ControlChange):
                    self.midi_out.send_message([0xB0 + event.channel, event.type, event.data_status])

                #wait until next event
                try:
                    time.sleep(buffer[i+1].delta)
                except IndexError:
                    if i < len(buffer)-1:
                        logger.debug("Skipped element %d out of %d", i, len(buffer))
```

This is my first experiment with midi and synthesizers and I am really lost. Maybe somebody here can give a hint about what I am doing wrong?

**Comment by SpotlightKid** [comment]
First off, when you start sfizz as a JACK client, you need use the JACK API with python-rtmidi, because sfizz will not have an ALSA MIDI input port.

This means instantiating `MidiOut` like this:

```py
midi_out = rtmidi.MidiOut(rtapi=rtmidi.UNIX_JACK)
```

Then you need to find out the port number of the sfizz JACK MIDI input port, which is called "sfizz:input". For example like so:

```py
try:
   port_number = midi_out.get_ports().index("sfizz:input")
except ValueError:
    print("Can't find port #sfizz:input'!")
    raise
```

and then open that port:

```py
midi_out.open_port(port_number)
```

Then you can start sending MIDI events to that port:

```py
def play_note(note, dur=1.0):
    midi_out.send_message([0x90, note, 64])
    time.sleep(dur)
    mo.send_message([0x80, note, 64])

play_note(60)
play_note(64)
play_note(67)
play_note(72)
```

You can simplify this using the `open_midiout` function from `rtmidi.midutil`:

```py
from rtmidi.midiutil import open_midiport

from rtmidi.midiutil import open_midioutput
midi_out, port_name = open_midioutput("sfizz:input", api=rtmidi.API_UNIX_JACK)
```

The first argument to `open_midioutput` can be a unambiguous sub-string of the MIDI port name.

Hope that helps!

**Comment by flixman** [comment]
Hi @SpotlightKid . Thank you for your answer!

At the end, I managed to make it work by:
1. I discovered there was another midi source created when I was running the program (```"Midi-Bridge:RtMidiOut Client:(capture_0) RtMidi output"```)
2. I connected that to sfizz:input by executing
```
pw-jack jack_connect  "Midi-Bridge:RtMidiOut Client:(capture_0) RtMidi output" sfizz:input
```
I have tried your approach, but does not work _for me_. I think is because I am using pipewire instead of jack. I have checked in the rtmidi code and I do not see any pipewire-related apis, so I guess is not supported by rtmidi by itself?

**Comment by SpotlightKid** [comment]
> I have checked in the rtmidi code and I do not see any pipewire-related apis, so I guess is not supported by rtmidi by itself?

There is no special API for Pipewire in python-rtmidi. Pipewire supports the JACK API. Maybe you need to re-compile python-rtmidi on your system.

See #210.

**Comment by flixman** [comment]
Indeed! I have just recompiled it and... it just worked :-O Thank you!
