### ISSUE TITLE
get_ports() missing

### ISSUE THREAD

**Issue by dhilowitz** [SpotlightKid/python-rtmidi#24]
Hi,

Thanks for a great library. I tried running the sample code and it seems that get_ports() method is missing. I get this:

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    available_ports = midiout.get_ports()
AttributeError: 'rtmidi_python.MidiOut' object has no attribute 'get_ports'
```

**Comment by dhilowitz** [comment]
FWIW, I'm running this on Mac OS X 10.12.6.

**Comment by SpotlightKid** [comment]
The Python module name of this package is `rtmidi` not `rtmidi_python`. Are you sure you installed the correct package?

**Comment by dhilowitz** [comment]
Hmm. That's confusing. When I do `pip install rtmidi`, I get this package: https://github.com/patrickkidd/pyrtmidi.

**Comment by SpotlightKid** [comment]
https://spotlightkid.github.io/python-rtmidi/installation.html#from-pypi

**Comment by dhilowitz** [comment]
Oh, my gosh! Apparently, I installed https://github.com/superquadratic/rtmidi-python instead of https://github.com/SpotlightKid/python-rtmidi. As soon as I did pip install python-rtmidi, .get_ports() started to work. Thanks for bearing with my confusion.

**Comment by SpotlightKid** [comment]
No worries, you're not the first one to get confused over these. :)
