### ISSUE TITLE
Update RtMidi to version 3

### ISSUE THREAD

**Issue by SpotlightKid** [SpotlightKid/python-rtmidi#25]
RtMidi version [3.0.0 is out](https://github.com/thestk/rtmidi/releases/tag/v3.0.0) with a few enhancements.

We need to update the `RtMidi.cpp` and `Rtmidi.h` sources and possibly adapt the `_rtmidi.pyx` wrapper.

**Comment by SpotlightKid** [comment]
The [rrtmidi3](https://github.com/SpotlightKid/python-rtmidi/tree/rtmidi3) branch now has the RtMidi sources updated to version 3 and added the new methods to set the client and port name.

Still missing tests, though.

**Comment by alexflex2000** [comment]
Thanks a lot for this new version. As a newbe, I'm still working on a way to record multiple midi tracks with rtmidi2. Playing tracks, while recording an other... But thank you so much for your work !  Alexis

**Comment by SpotlightKid** [comment]
The [rtmidi3](https://github.com/SpotlightKid/python-rtmidi/tree/rtmidi3) branch has been merged into `master` a while ago, but now I decided to include the RtMidi sources and header via a git sub-module instead, so it it is easier to update from upstream.

The sub-module points to the `python-rtmidi` branch of [a fork](https://github.com/SpotlightKid/rtmidi) (by me) of the upstream RtMidi repository, which incorporates changes and fixes by pull requests to the  upstream repository, which are (yet) unmerged, and some changes specific to python-rtmidi.

**Comment by SpotlightKid** [comment]
This is fixed now with [release 1.2.0](https://github.com/SpotlightKid/python-rtmidi/releases/tag/1.2.0).
