### ISSUE TITLE
Getting input messages

### ISSUE THREAD

**Issue by amirteymuri** [SpotlightKid/python-rtmidi#29]
Is there an example snippet code on how to get midi messages? For example from a running qtractor MIDI-track? How is it possible to get all midi-messages being played by a running qtractor?

**Comment by SpotlightKid** [comment]
Look in the `examples/basic` folder in the repo:

https://github.com/SpotlightKid/python-rtmidi/tree/master/examples/basic

**Comment by amirteymuri** [comment]
Thanks for the link!
