### ISSUE TITLE
use_virtual not obeyed in midiutil.open_midiinput if interactive=true

### ISSUE THREAD

**Issue by bolau** [SpotlightKid/python-rtmidi#30]
Hello,
thanks for this nice library!
The documentation for rtmidi.midiutil.open_midiport says:

> If port is None or no MIDI port matching the port number or name is available, should the user be prompted on the console whether to open a virtual MIDI port (if use_virtual is True) and/or with a list of available MIDI ports and the option to choose one? Defaults to True.

So I expected midiutil.open_midiinput(use_virtual=False, interactive=True) NOT to ask if I'd like to use a virtual port, but it does anyway.

In my opinion it but be great if use_virtual could be something like None or "prompt" (then ask), otherwise it should obey use_virtual=True or use_virtual=False.

What do you think?
Best, Boris

**Comment by SpotlightKid** [comment]
Yeah, the statement you quoted could be read that way but it doesn't actually say that `use_virtual == True` also means `interactive == False` ;) So the API currently doesn't provide a way to ask *only* whether to open a virtual port.

TBH, I initially only provided the functions in `midiutil` as an easy means to write short test scripts, expecting developers to implement their own functionality for selecting MIDI ports, based on the "official" API (`rtmidi.MidiBase.get_ports()`) for the user interface they need (e.g. within a GUI framework).

I could expand the range of values for the `use_virtual` parameter in the way you suggest, but I'm thinking whether it would not be better, to allow the developer to pass a function, which handles the prompting. This would be passed the port and the `use_virtual` value and would make it easier to integrate the `open_midiinput` / `open_midioutput` functions into different (user interface) frameworks.

**Comment by bolau** [comment]
> So the API currently doesn't provide a way to ask only whether to open a virtual port.
I meant it the other way 'round. I would like to be asked to choose from a list of Midi inputs without being asked to create a new virtual one. So `interactive == True` and `use_virtual == False`. But currently, use_virtual is ignored if `interactive == True`.

> TBH, I initially only provided the functions in midiutil as an easy means to write short test scripts, 
I see. I guess I could just use MidiIn.get_ports or MidiOut.get_ports. But what I found missing there is the possibility to get only input or only output ports, which the API in midiutil seems to provide. Am I mistaken there, can I filter somehow?

**Comment by SpotlightKid** [comment]
`MidiIn.get_ports()` only returns input ports and `MidiOut.get_ports()` only output ports. So you need to make an instance of each if you want to list input and output ports.

**Comment by bolau** [comment]
Ahh, I see. That was not clear from the documentation, I guess due to how the code/doc is created for these two classes. In that case, this is a non-issue. Thanks for your help!
