### ISSUE TITLE
Writing to disk and microtonal tunings

### ISSUE THREAD

**Issue by ghost** [SpotlightKid/python-rtmidi#32]
Not an issue but a question: 

1. Is it possible to write midi streams to disk as a midi file?

2. Is there a possibility of adjusting microtonal tunings on a single note on a single track?

**Comment by SpotlightKid** [comment]
re 1) When stiring MIDI data, it is usually necessary to add timing information and meta data. This is what the Standard MIDI File Format is for. See my miditk-smf library for handling SMF data.

**Comment by SpotlightKid** [comment]
re 2) I'm not sure, if I understand this question correctly. On-the-wire MIDI data has no concept of "tracks". python-rtmidi allows to send any valid MIDI ddata, though. Whether microtunings work, depends on whether the receiver supports the appropriate sysex commands.

**Comment by SpotlightKid** [comment]
No feedback. Closing this issue as invalid.
