### ISSUE TITLE
Broken on Python 3.7

### ISSUE THREAD

**Issue by tbodt** [SpotlightKid/python-rtmidi#33]
Python 3.7 made some changes to the interpreter state that broken Cython, and a fix was added to Cython 0.27.3 (https://github.com/cython/cython/issues/1955). The _rtmidi.cpp that's on PyPI was apparently compiled with an older version of Cython than that, so now you can't install python-rtmidi easily from PyPI.

**Comment by SpotlightKid** [comment]
I've just released version 1.1.1 which has an updated `src/_rtmidi.cpp`. Please let me know whether this installs cleanly and works for you.

**Comment by SpotlightKid** [comment]
No further feedback. Assuming solved.

**Comment by tbodt** [comment]
It is in fact solved, thanks for the quick update.
