### ISSUE TITLE
python-rtmidi.get_message() doesn't return system exclusive commands

### ISSUE THREAD

**Issue by Serhiy1** [SpotlightKid/python-rtmidi#37]
Hey there,
I'm currently trying to communicate with a device via midi.  I'm sending a message to poll for the device's current configuration and it returns up to 30 bytes of data.

I can use the library to successfully send the device data but I've come across some problems trying to receive messages.  

I've verified that the device is sending back data via the use of MIDI OX. 
![image](https://user-images.githubusercontent.com/28574129/46414612-62c62f80-c71b-11e8-9c71-8dc904cc499a.png)

I've also verified that get_message() works with conventional midi devices by running the same code with an oxygen8, So this leads me to believe that get_message does not listen to sysEx commands  

Here is the code that I have written so far in trying to communicate with the device

[midi.zip](https://github.com/SpotlightKid/python-rtmidi/files/2442311/midi.zip)

**Comment by SpotlightKid** [comment]
Have you enabled reception of SysEx messages with `midiout.ignore_types(sysex=False)` (where `midiout` is a `rtmidi.MidiOut` instance)?

https://spotlightkid.github.io/python-rtmidi/rtmidi.html#rtmidi.MidiIn.ignore_types

**Comment by Serhiy1** [comment]
Oh... -_-

Thanks for the help, I  thought I thoroughly red through the docs, but I guess that's not true.

**Comment by diegoherranz** [comment]
> Have you enabled reception of SysEx messages with `midiout.ignore_types(sysex=False)` (where `midiout` is a `rtmidi.MidiOut` instance)?
> 
> https://spotlightkid.github.io/python-rtmidi/rtmidi.html#rtmidi.MidiIn.ignore_types

This fixed it for me. Just a note in case it is useful to anyone, it is `rtmidi.MidiIn` and not `rtmidi.MidiOut`, but the link to the docs was correct anyway.

Thanks!

**Comment by SpotlightKid** [comment]
@diegoherranz Thanks for the report. I fixed the comment above.

**Comment by Erriez** [comment]
I was also investigating why received sysex messages are not returned by function `midiin.get_message()`. Finally I found the answer in this ticket.

I suggest to include a note in function `get_message()` that input sysex messages are filtered by default and must be explicitly enabled via `ignore_types(sysex=False)`.

Thanks.
