### ISSUE TITLE
Closing ports on Linux

### ISSUE THREAD

**Issue by teymuri** [SpotlightKid/python-rtmidi#39]
I am not sure this is because of rtmidi, but since i have been using mainly rtmidi and my Memory is completely full now after some hours of playing with midi stuff (The 8 GB memory is completely exhausted and also the Swap partition is almost full). I explicitly close all MidiIn MidiOut ports i open with close_port() method by closing the main program. Is there any possibility that the ports doesn't get closed properly?

**Comment by SpotlightKid** [comment]
Which version of python-rtmidi are you using? On which OS? Can you copy and paste how you are measuring memory usage and your memory statistics?

**Comment by teymuri** [comment]
I found out that it had nothing to do with rtmidi. Thanks for your reply!
