### ISSUE TITLE
Can't install on Raspbian Jessie Lite

### ISSUE THREAD

**Issue by stefets** [SpotlightKid/python-rtmidi#4]
Hi SpotlightKid !

After installing Raspbian Jessie Lite and the following packages : 
$ sudo apt-get install build-essential
$ sudo apt-get install libasound2-dev
$ sudo apt-get install libjack-dev
$ sudo apt-get install python-pip
**$ sudo pip install python-rtmidi**

The pip install python-rtmidi failed...

pi@RPI2:~ $ sudo pip install python-rtmidi
Downloading/unpacking python-rtmidi
  Could not find a version that satisfies the requirement python-rtmidi (from versions: 0.3.1a, 0.4.1b, 0.4.3b1, 0.3.1a, 0.3a, 0.4.2b, 0.5b1, 0.4.3b1, 0.2a, 0.3.1a, 0.3a, 0.2a, 0.5b1, 0.4.1b, 0.1a, 0.1a, 0.4.2b, 0.5b1, 0.4.2b, 0.4b, 0.4.3b1, 0.4.1b, 0.3a, 0.4b, 0.4b)
Cleaning up...
No distributions matching the version for python-rtmidi
Storing debug log for failure in /root/.pip/pip.log

Hardware : Raspberry PI 2

**Comment by stefets** [comment]
I was able to make it works with the the following ....

wget https://chrisarndt.de/projects/python-rtmidi/download/python-rtmidi-0.5b1.tar.gz
tar -xzf  python-rtmidi-0.5b1.tar.gz
cd python-rtmidi-0.5b1/
sudo python setup.py install

**Comment by SpotlightKid** [comment]
You need the `--pre` option when installing via `pip`, since `python-rtmidi`s version number still classifies it as a beta release. This is mentioned in the [installation](http://trac.chrisarndt.de/code/wiki/python-rtmidi/install) documentation linked from the homepage.
