### ISSUE TITLE
Installing without Jack

### ISSUE THREAD

**Issue by randombyte-developer** [SpotlightKid/python-rtmidi#41]
I am using ALSA midi, Jack isn't needed for me. But when installing this with pip, it wanted Jack to be installed. On my system installing `libjack0` or `libjack-dev` would remove other packages (I don't know exactly why). After some googling I found that 

`pip install python-rtmidi --install-option="--no-jack"`

is just the right thing. This should be included somewhere in the docs.

**Comment by randombyte-developer** [comment]
:+1:

**Comment by SpotlightKid** [comment]
The `setup.py` options are now listed in the [installation instructions](https://spotlightkid.github.io/python-rtmidi/installation.html#from-source), and some other improvements to the same document have been made (5ecb48fb3668ccd812638a7a94caa843ec452927).
