### ISSUE TITLE
Sample program doesn't play

### ISSUE THREAD

**Issue by vshesh** [SpotlightKid/python-rtmidi#43]
I just pip installed, pasted the sample program into a python file, and ran
`python3 test.py` 

I got: 
```
Cannot connect to server socket err = No such file or directory
Cannot connect to server socket
jack server is not running or cannot be started
```

which i think are fluidsynth errors and then the program hangs. 
am i missing something?

also would like to know if this is the right program to install if I want to start a process that listens for midi events and plays them realtime. i'm working on a interface that is supposed to play sound in response to events in the real world.

System Details;
Mac OS X 10.13.2
Python 3.7.2
FluidSynth 2.0.4

i don't have jack, but mac os x has coremidi so it should work still?

**Comment by SpotlightKid** [comment]
> I just pip installed, pasted the sample program into a python file, and ran `python3 test.py`

You mean the code on the [usage page](https://spotlightkid.github.io/python-rtmidi/usage.html) of the documentation?

Please note that this is basically the same as [examples/basic/midiout.py}(https://github.com/SpotlightKid/python-rtmidi/blob/master/examples/basic/midiout.py), only the latter uses `rtmidi.midiutil.open_midioutput` to open a MIDI output port, which allows you to select interactively which output port you want to use.

> I got:

> ```
> Cannot connect to server socket err = No such file or directory
>Cannot connect to server socket
> jack server is not running or cannot be started
> ```

This is an error from the rtmidi JACK API backend, which tries to connect to a JACK server, but JACK isn't running.

Normally, on OS X, if you compiled in support for CoreMIDI and JACK, the former should be the default, when you create a `rtmidi.MidiOut` or `rtmidi.MidiIn` instance. You can specify which API backend to use with the `rtapi` argument, [when instantiating](https://spotlightkid.github.io/python-rtmidi/rtmidi.html#rtmidi.MidiOut). If you use `rtmidi.midiutil.open_midiout` or `rtmidi.midiutil.open_midiin`, you can also select the backend API via the `RTMIDI_API` [environment variable](https://github.com/SpotlightKid/python-rtmidi/blob/master/rtmidi/midiutil.py#L46), e.g. `RTMIDI_API=UNIX_JACK` or `RTMIDI_API=MACOSX_CORE`.

> also would like to know if this is the right program to install if I want to start a process that listens for midi events and plays them realtime.

You don't really need (python-)rtmidi for this. Fluidsynth opens its own MIDI input port, which you can just connect to the output from another program or to the input from your MIDI interface. But you can open Fluidsynth's MIDI input from python-rtmidi and send MIDI data to it from your program.

To make it absolutely clear: python-midi doesn't interpret MIDI data in any way nor does it render MIDI to audio. It's sole purpose is to get MIDI data from a MIDI interface or another program, which has opened a MIDI output port, into your program or send MIDI dat from your program to a MIDI interface or another program, which has opened a MIDI input port.

**Comment by vshesh** [comment]
Ok... thank you for your response.

The fluidsynth binding libraries don't work for me (some internal ctypes errors) so I was hoping I could use this one.
I tried the sample code you linked to instead and got a different error:

```python
Traceback (most recent call last):
  File "scamp_test.py", line 46, in <module>
    midiout, port_name = open_midioutput(port, "output")
  File "/usr/local/lib/python3.7/site-packages/rtmidi/midiutil.py", line 268, in open_midioutput
    client_name, port_name)
  File "/usr/local/lib/python3.7/site-packages/rtmidi/midiutil.py", line 188, in open_midiport
    midiobj = midiclass_(api, name=client_name)
  File "src/_rtmidi.pyx", line 930, in rtmidi._rtmidi.MidiOut.__cinit__
TypeError: an integer is required
DN0a22467e:harmonious Vishesh$ python3 scamp_test.py 0
DEBUG:rtmidi.midiutil:Creating MidiOut object.
Traceback (most recent call last):
  File "scamp_test.py", line 46, in <module>
    midiout, port_name = open_midioutput(port, "output")
  File "/usr/local/lib/python3.7/site-packages/rtmidi/midiutil.py", line 268, in open_midioutput
    client_name, port_name)
  File "/usr/local/lib/python3.7/site-packages/rtmidi/midiutil.py", line 188, in open_midiport
    midiobj = midiclass_(api, name=client_name)
  File "src/_rtmidi.pyx", line 930, in rtmidi._rtmidi.MidiOut.__cinit__
TypeError: an integer is required
```

I'm not sure what's going on there. It's an exact copy paste of that example.

**Comment by SpotlightKid** [comment]
Dang. There is in fact an error in the `midiout.py` example on line 26. :(  Sorry for that. I just pushed a fix.

**Comment by SpotlightKid** [comment]
> The fluidsynth binding libraries don't work for me (some internal ctypes errors) so I was hoping I could use this one.

So you want to run `fluidsynth` as a separate process and then send MIDI generated by your Python program to it using `python-rtmidi`? That's certainly possible. You can look at the [examples/sequencer/sequencer.py](https://github.com/SpotlightKid/python-rtmidi/blob/master/examples/sequencer/sequencer.py) for a basic way of queueing MIDI messages - but it's certainly no full-featured sequencer.

**Comment by vshesh** [comment]
Ok, I saw the fix and applied it to the example, so now it's just     
`midiout, port_name = open_midioutput(port)`

now what i get is that the process starts, shows me the same errors, and then hangs.
I don't see `print("Sending NoteOn event.")` ever fire.

I think it's still stuck finding a port and I'm not sure why.
If I'm understanding whats happening here, rtmidi tries to start up fluidsnyth, and then everything hangs.

**Comment by SpotlightKid** [comment]
It seems to me that your version of python-rtmidi was compiled with JACK support. The macOS binary wheels provided on PyPI do not have JACK support compiled in, so it seems that you either compiled python-rtmidi yourself or got a binary distribution from somewhere else. If you compiled it yourself (`pip install python.rtmidi` may have done that automatically for you), it seems that you have JACK installed on your system, otherwise JACK support would not have been compield into your python-rtmidi version.

Can you confirm this by runningg this in an interactive python session:

    >>> import rtmidi
    >>> rtmidi.get_compiled_api()

If you installed the binary wheels from PyPI, this should return `[1]`. If JACK support was compiled in, the list should also contain `3` (i.e. the constant `rtmidi.API_UNIX_JACK`).

**BUT**: regardless of the above, it seems to me that you have a wrong conception of what python-rtmidi does. python-rtmidi does not include fluidsynth, or start it, or talk to it in any way if you don't tell it to. It solely manages MIDI input and output. It does not generate any audio (on its own).

**Comment by SpotlightKid** [comment]
Closing due to no further feedback.
