### ISSUE TITLE
Release archives are missing src/rtmidi/RtMidi.cpp

### ISSUE THREAD

**Issue by brulzki** [SpotlightKid/python-rtmidi#45]
I'm writing an ebuild for Gentoo. It fails to build release 1.3 because the RtMidi.cpp source files (from the git submodule) are missing. Error is:
`x86_64-pc-linux-gnu-g++: error: src/rtmidi/RtMidi.cpp: No such file or directory`

It works for building release 1.1.2 (before the submodule).
Source is fetched from https://github.com/SpotlightKid/python-rtmidi/archive/1.3.0.tar.gz

Any chance that the sources can be included in the release tarballs?

**Comment by SpotlightKid** [comment]
The RtMidi source are included in the repo as a git sub-module.

AFAIK, Github does not support including git submodules in the release archives. Github creates these archive automatically when you tag a release. I don't know how to prevent this or remove them. but they shouldn't be used.

The canonical source distribution is always the one found on the PyPI page:

https://pypi.org/project/python-rtmidi/#files

**Comment by SpotlightKid** [comment]
You can always use a URL of the following form, which doesn't include a hash, so only the version number changes:

    https://files.pythonhosted.org/packages/source/p/python-rtmidi/python-rtmidi-$VERSION.tar.gz

**Comment by brulzki** [comment]
Thanks. That works too
