### ISSUE TITLE
Custom sf2 with python-rtmidi

### ISSUE THREAD

**Issue by DJ-Hayden** [SpotlightKid/python-rtmidi#46]
Hello! I was looking at pyfluidsynth and was having some issues getting the sound to play (I opened an issue there). While troubleshooting I also found this and was wondering if python-rtmidi can work with SF2 files of various instruments?

**Comment by SpotlightKid** [comment]
For reference: the above mentioned pyfluidsynth issue is https://github.com/nwhitehead/pyfluidsynth/issues/22

**Comment by SpotlightKid** [comment]
python-rtmidi is not directly comparable to (py)fluidsynth. It solely manages real-time MIDI input and output via MIDI devices provided by the underlying OS-dependent MIDI framework (e.g. ALSA, JACK, CoreMIDI or Windows MultiMedia). It does not generate any audio on its own and therefor also does not use SF2 sound fonts.

Furthermore, it also does not handle Standard MIDI Files (SMF), it only enables the reception and sending of real-time MIDI data. For that you might want to have a look at https://github.com/SpotlightKid/miditk-smf or other MIDI file libraries.

**Comment by SpotlightKid** [comment]
Closing due to no further requests for information.
