### ISSUE TITLE
 #include "RtMidi.h"

### ISSUE THREAD

**Issue by mhansinger** [SpotlightKid/python-rtmidi#47]
Hi,
I tried to install pyhton-rtmidi on my raspi via `setup.py install`. Cython is also installed. However, I get following error:
`Package jack was not found in the pkg-config search path.
Perhaps you should add the directory containing `jack.pc'
to the PKG_CONFIG_PATH environment variable
No package 'jack' found
running install
running bdist_egg
running egg_info
writing top-level names to python_rtmidi.egg-info/top_level.txt
writing dependency_links to python_rtmidi.egg-info/dependency_links.txt
writing python_rtmidi.egg-info/PKG-INFO
reading manifest file 'python_rtmidi.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'src/rtmidi/RtMidi.cpp'
warning: no files found matching 'src/rtmidi/RtMidi.h'
warning: no previously-included files found matching '.appveyor.yml'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching '*.rst.in'
no previously-included directories found matching 'ci'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'python_rtmidi.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
running build_ext
building 'rtmidi._rtmidi' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-6waWnr/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc/rtmidi -I/usr/include/python3.5m -c src/_rtmidi.cpp -o build/temp.linux-armv7l-3.5/src/_rtmidi.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
src/_rtmidi.cpp:650:20: fatal error: RtMidi.h: No such file or directory
 #include "RtMidi.h"
                    ^
compilation terminated.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
`

Any idea how to fix this?
Thanks

**Comment by SpotlightKid** [comment]
Did you download the source archive from Github "releases" page? Then see my answer to issue #45.

Please see the [installation documention](https://spotlightkid.github.io/python-rtmidi/installation.html#from-the-source-distribution) on how to install from the source.

**Comment by SpotlightKid** [comment]
Closing due to no further feedback.
