### ISSUE TITLE
midioutwrapper.py is broken

### ISSUE THREAD

**Issue by jmeile** [SpotlightKid/python-rtmidi#51]
Hi

when running the midioutwrapper.py example, it fires:

```
traceback (most recent call last):
  File "midioutwrapper.py", line 19, in <module>
    from rtmidi.midiconstants import (ALL_NOTES_OFF, ALL_SOUND_OFF, BALANCE, BANK_SELECT_LSB,
ImportError: cannot import name 'MODULATION' from 'rtmidi.midiconstants' (C:\Program Files (x86)\Python37-32\lib\site-packages\rtmidi\midiconstants.py)
```

Indeed the constant: "MODULATION" isn't defined unter: midiconstants.py. I guess you mean here: "MODULATION_WHEEL"

By the way, after replacing: "MODULATION" by "MODULATION_WHEEL", i got:
```
Traceback (most recent call last):
  File "midioutwrapper.py", line 230, in <module>
    with mout.open_virtual_port():
  File "src\_rtmidi.pyx", line 613, in rtmidi._rtmidi.MidiBase.open_virtual_port
NotImplementedError: Virtual ports are not supported by the Windows MultiMedia API.
```

So, I guess you better use the following call instead:
mout, in_port = midiutil.open_midioutput()

Or at least detect if you are using windows, then call the right function.

Anyway, after having done those changes, I'm using both: midioutwrapper.py and midiin_callback.py together with the virtual ports defined by a software called Bome Translator, but the midiin_callback.py script doesn't captures anything sent by the midioutwrapper.py script. Is this perhaps a problem with the Windows MIDI implementation?

Best regards
Josef

**Comment by SpotlightKid** [comment]
Should be fixed in b3ba6b2 and b563436.

**Comment by SpotlightKid** [comment]
> the midiin_callback.py script doesn't captures anything sent by the midioutwrapper.py script.

Works here:

```
$ python examples/basic/midiin_callback.py 
DEBUG:rtmidi.midiutil:Creating MidiIn object.
Do you want to create a virtual MIDI input port? (y/N) y
INFO:rtmidi.midiutil:Opening virtual MIDI input port.
Attaching MIDI input callback handler.
Entering main loop. Press Control-C to exit.
```

```
$ python examples/advanced/midioutwrapper.py 
Do you want to create a virtual MIDI output port? (y/N) n
Available MIDI ports:

[0] Midi Through:Midi Through Port-0 14:0
[1] RtMidiIn Client:Virtual MIDI input 128:0

Select MIDI output port (Control-C to exit): 1
Press key to send test messsage to port 'RtMidiIn Client:Virtual MIDI input 128:0'...
```

When I press enter after the prompt in the last line, the MIDI messages appear in the terminal where `midiin_callback` is running:

```
[Virtual MIDI input] @1576012180.063243 [194, 40]
[Virtual MIDI input] @1576012180.063285 [146, 60, 127]
[Virtual MIDI input] @1576012181.064439 [130, 60, 0]
```

On Windows, since you can't use virtual ports, you either have to use something like [loopMIDI](https://www.tobias-erichsen.de/software/loopmidi.html) or use hardware MIDI ports with a real cable loop.

**Comment by jmeile** [comment]
I actually tested the code by sending messages to Bome Translator and there the messages from midioutwrapper.py will be captured. I really don't know why it is not working if I send them to the midiin_callback.py script. I'm using the same virtual ports, which are called: "Bome Midi Translator 1". I will see if with loopMIDI or with the USB to MIDI cable works.

**Comment by jmeile** [comment]
Anyway, I must say that the midioutwrapper.py code looks great and I will probably use it.

Thanks for sharing

**Comment by jmeile** [comment]
Ok, I tried both scripts with the Bome Translator software and it works. I guess, I can't use those virtual ports without the software. So, it seems that there is no issue under Windows.

**Comment by jmeile** [comment]
By the way, thanks for pointing loopMIDI. It is really useful for debugging my MIDI application before trying it with the real hardware.
