### ISSUE TITLE
why I get rtmidi.NoDevicesError exception?

### ISSUE THREAD

**Issue by lorenzofattori** [SpotlightKid/python-rtmidi#53]
Trying to run the basic example to receive midi notes with callback and I get the following:

rtmidi._rtmidi.NoDevicesError: No MIDI input ports found.

OS: Windows 10

any idea what can be wrong?

**Comment by SpotlightKid** [comment]
Do you have a MIDI interface with a MIDI input port plugged in? The Windows MultiMedia System API does not have a default MIDI device or port. Alternatively you can use virtual MIDI devices provided by something like [loopMIDI](https://www.tobias-erichsen.de/software/loopmidi.html).

**Comment by lorenzofattori** [comment]
aha, that was easy... woops.
Sorry, I worked only with Mac till now... maybe is nice to add one line to the quick start or example to make it clear for dumbs like me!

Thank you
