### ISSUE TITLE
[FoxDot] AttributeError: module 'rtmidi' has no attribute 'MidiIn'

### ISSUE THREAD

**Issue by celinanperalta** [SpotlightKid/python-rtmidi#54]
I'm trying to sync FoxDot with an external MIDI clock, but I am getting the following output:
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/FoxDot/lib/Code/main_lib.py", line 155, in __call__
    exec(self._compile(code), self.namespace)
  File "FoxDot", line 1, in <module>
    from __future__ import absolute_import, division, print_function
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/FoxDot/lib/TempoClock.py", line 445, in sync_to_midi
    self.midi_clock = MidiIn(port)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/FoxDot/lib/Midi.py", line 61, in __init__
AttributeError: module 'rtmidi' has no attribute 'MidiIn'`

I've tried re-installing rtmidi, but I'm not sure what would be causing this problem.

**Comment by SpotlightKid** [comment]
Are you sure, you are installing the correct package, i.e. [python-rtmidi](https://pypi.org/project/python-rtmidi/)? (not `"rtmidi-python"` or `"rtmidi"`!).

**Comment by celinanperalta** [comment]
Yes, I installed python-rtmidi.

**Comment by celinanperalta** [comment]
Now I'm getting: NameError: name '_err' is not defined

**Comment by SpotlightKid** [comment]
Can you try the following:

```
$ python
Python 3.8.1 (default, Dec 21 2019, 20:57:38) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rtmidi
>>> rtmidi.__file__
'/usr/lib/python3.8/site-packages/rtmidi/__init__.py'
>>> rtmidi._rtmidi.__file__
'/usr/lib/python3.8/site-packages/rtmidi/_rtmidi.cpython-38-x86_64-linux-gnu.so'
>>> rtmidi.get_compiled_api()
[2, 3]
>>> rtmidi.MidiIn
<class 'rtmidi._rtmidi.MidiIn'> 
```
(your output will be different on macOS.) 

Please post your input and output here.

**Comment by celinanperalta** [comment]
```
MacBook-Pro:~ celinaperalta$ python3
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rtmidi
>>> rtmidi.__file__
'/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rtmidi/__init__.py'
>>> rtmidi.MidiIn
<class 'rtmidi._rtmidi.MidiIn'>
>>> 
```

**Comment by SpotlightKid** [comment]
You missed the most important bit:
 
```
>>> rtmidi._rtmidi.__file__
'/usr/lib/python3.8/site-packages/rtmidi/_rtmidi.cpython-38-x86_64-linux-gnu.so'
```

But, anyway, as you can see `rtmidi.MidiIn` is defined, so the error is in your project. Make sure you do not have a file called `rtmidi.py` in your project or anywhere else on your `PYTHONPATH`.

**Comment by celinanperalta** [comment]
Alright, I'll check it out again. Thanks.
