### ISSUE TITLE
It would be nice to enable back linking to your repository

### ISSUE THREAD

**Issue by jmeile** [SpotlightKid/python-rtmidi#58]
Hi

I don't know if "back linking" is the correct term, but if I go to my project dependencies:
https://github.com/jmeile/JMMidiBassPedalController/network/dependencies

Then I see the listed dependencies on the requirements.txt file. If you look carefully at my dependencies, you will see that the other two repositories listed there: "sissaschool / xmlschema" and "mzipay / Autologging Autologging" have a link to the repository. Yours however, is greyed out.

It would be nice if you enable this feature. By doing it, I guess you can also see the repositories depending on yours (Dependends). I find this quite interesting because I could see if on the Dependends there are similar projects to mine or even new projects that may be interesting.

Best regards
Josef

**Comment by jmeile** [comment]
Well after googling for:
**"We haven’t found any dependents for this repository yet."**

which is the message that appears when clicking on your repository's dependents, I found this:

https://stackoverflow.com/questions/56341992/github-we-haven-t-found-any-dependents-for-this-repository-yet

It seems that the issue is related to the git repository name or your username. I'm not sure what the exact problem on your case it. I guess this is a kind of but from GitHub :-(

**Comment by SpotlightKid** [comment]
So, there's nothing I can do about it, I guess? I might have something to do with the fact, that the project `url` set in `setup.py` is not  a Github URL?

But I want change my Github username or the project meta-data just to appease a broken convenience feature.

**Comment by jmeile** [comment]
To be honest, I don't know if you can do something, but the URL may be also a reason.

Anyway, is up to you to solve this. It would be just nice to see which project depend on yours, then one could see if there are similar or useful projects.

And yes, if I were you, I wouldn't change the username or project meta-data.

**Comment by SpotlightKid** [comment]
Closing this as wontfix, however, I have listed JMMidiBassPedalController here:

https://github.com/SpotlightKid/python-rtmidi/wiki/Projects-using-python-rtmidi

**Comment by jmeile** [comment]
Thanks for adding my project there and for the list. There are indeed some interesting projects there.
