### ISSUE TITLE
Refresh connected port info without instantiation

### ISSUE THREAD

**Issue by gulaki** [SpotlightKid/python-rtmidi#59]
I am working in Windows 10 + Python 3.7

I am trying to prototype a long-running realtime interactive
system that can react to keyboard input and process MIDI.

MIDI ports can be connected or disconnected during the lifetime
of the main Python program. The first issue:

Trying to find if there are MIDI input ports requires 
instantiating a `rtmidi.MIDIIn()` and then call its
`get_ports()` method. If no input ports exist, this results in an error 
in the stderr stream. 

    >>> import rtmidi
    >>> portin = rtmidi.MidiIn()
    MidiInWinMM::initialize: no MIDI input devices currently available.
    >>> portin.get_ports()
    []
    
During the lifetime of the program, if a new MIDI input port
is added to the system, it successfully detects it, and is usable.

    >>> portin.get_ports()
    ['loopMIDI Port 0']
    >>> portin.open_port()
    <rtmidi._rtmidi.MidiIn at 0x24d68de7e08>
    >>> portin.close_port()

The second issue:
If now the MIDI port is removed externally, and we try
to list the available ports by creating a new instance,

    >>> b = rtmidi.MidiIn()
    >>> b.get_ports()
    ['loopMIDI Port 0']

Still shows the old port. If we try to open this port, we get an error.

    >>> b.open_port()
    ---------------------------------------------------------------------------
    SystemError                               Traceback (most recent call last)
    <ipython-input-20-4cc2ecc4bd19> in <module>
    ----> 1 b.open_port()
    
    src\_rtmidi.pyx in rtmidi._rtmidi.MidiBase.open_port()
    
    src\_rtmidi.pyx in rtmidi._rtmidi._cb_error_func()
    
    src\_rtmidi.pyx in rtmidi._rtmidi._default_error_handler()
    
    SystemError: MidiInWinMM::openPort: error creating Windows MM MIDI input port.

Is there a way to query what ports exist without instantiating
a `MidiOut` or `MidiIn` object? Is there a way to suppress C++ level 
exceptions that dont break Python? [First issue]

Is there a way to refresh port information? [Second issue]

Or should we discourage the user from modifying ports during runtime?

**Comment by SpotlightKid** [comment]
> Is there a way to query what ports exist without instantiating a MidiOut or MidiIn object?

No. For most (all?) backend APIs, creating a `MidiIn` or `MidiOut` instance creates a client for the underlying MIDI framework, e.g. an ALSA sequencer client, or a JACK client, which connects to the JACK server. Without such a client it would not be possible to get a list of ports. I'm not 100% sure what the situation on Windows is, but anyway, that's how the RtMidi API works. It's a C++ API, so it is class-based.

The `"no MIDI input devices currently available"' message is only a warning, it is generated by the C++ code, so you can not prevent it from being generated in `python-rtmidi, but you should be able to suppress it. The [default error handler](https://github.com/SpotlightKid/python-rtmidi/blob/6f68cd8202966f22ea718cfffc4218cd743f27c8/src/_rtmidi.pyx#L405) (which can be overwritten via the `set_error_handler`) turns RtMidi errors of type `ERR_WARNING` into calls to `warning.warn`, i.e. a [warnings.UserWarning](https://docs.python.org/3/library/exceptions.html#UserWarning). See the standard library documentation on how to filter warnings.

> Is there a way to refresh port information?

Creating a new instance should give you up-to-date port infomration. if that#s not the case on Windows, that's a bug, IMHO, and should be [reported upstream](https://github.com/thestk/rtmidi/issues) (if possible, verifying first that the error exists with the pure C++ API)..

**Comment by gulaki** [comment]
I did some investigation and the following algorithm:

- Opens an input port, finds no ports, outputs warning
- Waits till MIDI input port connected, user presses enter.
- Finds the connected port and opens it
- Registers a simple callback and records inputs 
  from port for 2 secs.
- Stops recording
- Waits for user to disconnect MIDI ports.
- Looks for ports again to see that ports have vanished
- If the old ports are found, try to open them

I saved the Python script in `midiinput.py`. The script should be run
with all MIDI input ports disconnected. 

    import time
    import rtmidi
    import warnings
    
    print("Start with no input ports.")
    
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
    
        inport = rtmidi.MidiIn()
        ports = inport.get_ports()
        print(f"Available ports: {ports}")
    
        input("Attach MIDI input device and press enter: ")
        inport = rtmidi.MidiIn()
        ports = inport.get_ports()
        print(f"Available ports: {ports}")
    
        def input_callback(msg, data):
            print(msg, data)
            
        if ports:
            start = time.time()
            inport.set_callback(input_callback)
    
            with inport.open_port(0):
                while time.time() - start < 2.0:
                    pass
            inport.cancel_callback()
            print("Sleeping 1 sec to verify no more input")
            time.sleep(1)
        else:
            print("No input ports detected.")
            
        input("Remove MIDI input device and press enter.")
    
        inport = rtmidi.MidiIn()
        ports = inport.get_ports()
    
        print(f"Available ports: {ports}")
    
        if ports:
            start = time.time()
            inport.set_callback(input_callback)
    
            with inport.open_port(0):
                while time.time() - start < 2.0:
                    pass
            inport.cancel_callback()
        else:
            print("rtmidi successfully detects no ports")

**First issue:** I ran this script with my Nektar Impact LX25 MIDI
keyboard. It runs without a problem and `rtmidi` successfully detects 
when a new port is connected or disconnected. 

    Start with no input ports.
    
    MidiInWinMM::initialize: no MIDI input devices currently available.
    
    Available ports: []
    Attach MIDI input device and press enter:
    Available ports: ['Impact LX25+ 0', 'MIDIIN2 (Impact LX25+) 1']
    ([146, 62, 36], 0.0) None
    ([146, 53, 29], 0.012) None
    ([130, 62, 0], 0.212) None
    ([130, 53, 0], 0.012) None
    ([146, 57, 48], 0.244) None
    ([130, 57, 0], 0.179) None
    ([146, 59, 60], 0.298) None
    ([146, 60, 63], 0.01) None
    ([130, 60, 0], 0.059000000000000004) None
    ([130, 59, 0], 0.011) None
    Sleeping 1 sec to verify no more input
    Remove MIDI input device and press enter.
    
    MidiInWinMM::initialize: no MIDI input devices currently available.
    
    Available ports: []
    rtmidi successfully detects no ports

However, running the same script with LoopMIDI virtualized
ports on Windows seems to cause the problem. The output is as 
follows:

    Start with no input ports.
    
    MidiInWinMM::initialize: no MIDI input devices currently available.
    
    Available ports: []
    Attach MIDI input device and press enter:
    Available ports: ['loopMIDI Port 0']
    Sleeping 1 sec to verify no more input
    Remove MIDI input device and press enter.
    Available ports: ['loopMIDI Port 0']
    Traceback (most recent call last):
      File "test_rtmidi.py", line 46, in <module>
        with inport.open_port(0):
      File "src\_rtmidi.pyx", line 588, in rtmidi._rtmidi.MidiBase.open_port
      File "src\_rtmidi.pyx", line 223, in rtmidi._rtmidi._cb_error_func
      File "src\_rtmidi.pyx", line 411, in rtmidi._rtmidi._default_error_handler
    rtmidi._rtmidi.SystemError: MidiInWinMM::openPort: error creating Windows MM MIDI input port.

**`rtmidi` behaves as expected with a standardized physical MIDI
hardware**, and causes the error with LoopMIDI virtual MIDI ports.
Probably means LoopMIDI is not dropping the port on its own.

**Second issue:** The warning doesn't get suppressed.

I looked at the [default error handler](https://github.com/SpotlightKid/python-rtmidi/blob/6f68cd8202966f22ea718cfffc4218cd743f27c8/src/_rtmidi.pyx#L405)
function. It does invoke `warnings.warn()`. So we should be
able to suppress it with 

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        ...

As seen in the output this does not suppress the warning.
 I also tried executing the stript with the ignore 
 warning flag, as

    $ python -Wi midiinput.py

also doesn't suppress the warning. Maybe I am missing something.

**Question**: Do you think it is possible to open multiple instances
of `rtmidi.MidiOut()` and `open_port()` the same port number on them?

I would like to have different threads sending messages on different 
MIDI channels but through the same port. Or should I think about
serializing the messages before sending to port?

**Comment by SpotlightKid** [comment]
> As seen in the output this does not suppress the warning.

Unfortunately, if I read the code correctly, this seems to be a logic error in the RtMidi code. You can't attach an error handling function to a `RtMidi*` C++ class instance until you created one, yet the the constructor already uses the `error` function, but at that point no error handling function, which could handle the warning, has been attached yet. :(

**Comment by gulaki** [comment]
At first I did not understand your explanation. So I forked your repo and did some debugging, ran your tests, and came to the same conclusion. 
`MidiInWinMM :: Initialize`  in `rtmidi.cpp` is raising the `RtMidiError::Warning` before `_default_error_handler()` is getting assigned as callback.
So I guess I just have to live with it for now.

**Comment by SpotlightKid** [comment]
> `MidiInWinMM :: Initialize`  in `rtmidi.cpp` is raising the `RtMidiError::Warning` before `_default_error_handler()` is getting assigned as callback.

Correct.

> So I guess I just have to live with it for now.

Since I include my own fork of `RtMidi` as a sub-module in `python-rtmidi`, I guess I could fix this. What would you suggest, how this should be handled? Just remove the call to `error` in `MidiInWinMM :: Initialize`?

**Comment by SpotlightKid** [comment]
> Do you think it is possible to open multiple instances
of rtmidi.MidiOut() and open_port() the same port number on them?

Yes, that should be possible, at least on Linux with the ALSA and JACK backend that works and shows up as one Client with two outputs. Whether this works with the WindowsMM backend I'm unsure, probably not, since access to MIDI devices is usually exclusive with this API. You'd probably need loopMIDI or a similar virtual MIDI device helper for that.

**Comment by gulaki** [comment]
> Since I include my own fork of `RtMidi` as a sub-module in `python-rtmidi`, I guess I could fix this. What would you suggest, how this should be handled? Just remove the call to `error` in `MidiInWinMM :: Initialize`?

Yes, that would be great. Then I can send the no input devices warning from Python end when code sees that number of ports is zero. I can also send the message to whatever front-end I choose, while keeping the standard output clean.

> Yes, that should be possible, at least on Linux with the ALSA and JACK backend ...

I am still in the design phase with this part. Thinking along the line to `rtmidiport.send(msg)` from multiple threads to the same open port as the ouput to the port should be threadsafe. Dont know if messages can get lost. Will have to experiment when I write that part.

**Comment by SpotlightKid** [comment]
@gulaki Can you test #62? (See https://spotlightkid.github.io/python-rtmidi/install-windows.html for compiling on Windows)

**Comment by gulaki** [comment]
Sorry to get back to you late. I cloned the `feature/59/suppress-warnings` branch.
unzipped into a directory, ran inside a new conda environment.

both the commands 

`python-rtmidi> pip install .`

and

`python-rtmidi> python setup.py` errored out saying no file `rtmidi.h` found.

**Comment by SpotlightKid** [comment]
You need to run `git sub module update --init` after check out.

**Comment by SpotlightKid** [comment]
That doesn't work when you download the branch as a Zip, though. You need to check it out with `git clone https://github.com/SpotlightKid/python-rtmidi`.

**Comment by gulaki** [comment]
**Following is the full transcript of my terminal interaction. Here i first clone the repo, then checkout the `feature/59/suppress-warnings` branch, and then install it.**

(rtmidi-dev) D:\Python\python-rtmidi>git clone https://github.com/SpotlightKid/python-rtmidi
Cloning into 'python-rtmidi'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 2990 (delta 7), reused 13 (delta 4), pack-reused 2970
Receiving objects: 100% (2990/2990), 1.57 MiB | 671.00 KiB/s, done.
Resolving deltas: 100% (1806/1806), done.

(rtmidi-dev) D:\Python\python-rtmidi>dir
 Volume in drive D has no label.
 Volume Serial Number is D019-F367

 Directory of D:\Python\python-rtmidi

10-04-2020  15:19    <DIR>          .
10-04-2020  15:19    <DIR>          ..
10-04-2020  15:19    <DIR>          python-rtmidi
29-03-2020  21:39             1,182 test_rtmidi.py
               1 File(s)          1,182 bytes
               3 Dir(s)  60,096,667,648 bytes free

(rtmidi-dev) D:\Python\python-rtmidi>cd python-rtmidi

(rtmidi-dev) D:\Python\python-rtmidi\python-rtmidi>git checkout feature759/suppress-warnings
error: pathspec 'feature759/suppress-warnings' did not match any file(s) known to git

(rtmidi-dev) D:\Python\python-rtmidi\python-rtmidi>git checkout feature/59/suppress-warnings
Switched to a new branch 'feature/59/suppress-warnings'
Branch 'feature/59/suppress-warnings' set up to track remote branch 'feature/59/suppress-warnings' from 'origin'.

(rtmidi-dev) D:\Python\python-rtmidi\python-rtmidi>python setup.py install
Compiling src\_rtmidi.pyx because it changed.
[1/1] Cythonizing src\_rtmidi.pyx
running install
running bdist_egg
running egg_info
creating python_rtmidi.egg-info
writing python_rtmidi.egg-info\PKG-INFO
writing dependency_links to python_rtmidi.egg-info\dependency_links.txt
writing top-level names to python_rtmidi.egg-info\top_level.txt
writing manifest file 'python_rtmidi.egg-info\SOURCES.txt'
reading manifest file 'python_rtmidi.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'src\rtmidi\RtMidi.cpp'
warning: no files found matching 'src\rtmidi\RtMidi.h'
warning: no previously-included files found matching '.appveyor.yml'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching '*.rst.in'
no previously-included directories found matching 'ci'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'python_rtmidi.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-3.7
creating build\lib.win-amd64-3.7\rtmidi
copying rtmidi\midiconstants.py -> build\lib.win-amd64-3.7\rtmidi
copying rtmidi\midiutil.py -> build\lib.win-amd64-3.7\rtmidi
copying rtmidi\release.py -> build\lib.win-amd64-3.7\rtmidi
copying rtmidi\__init__.py -> build\lib.win-amd64-3.7\rtmidi
running build_ext
building 'rtmidi._rtmidi' extension
creating build\temp.win-amd64-3.7
creating build\temp.win-amd64-3.7\Release
creating build\temp.win-amd64-3.7\Release\src
creating build\temp.win-amd64-3.7\Release\src\rtmidi
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -D__RTMIDI_SILENCE_WARNINGS__ -D__WINDOWS_MM__ -Isrc\rtmidi -IC:\Users\Anustuv\.conda\envs\rtmidi-dev\include -IC:\Users\Anustuv\.conda\envs\rtmidi-dev\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpsrc\_rtmidi.cpp /Fobuild\temp.win-amd64-3.7\Release\src\_rtmidi.obj /EHsc
_rtmidi.cpp
src\_rtmidi.cpp(666): fatal error C1083: Cannot open include file: 'RtMidi.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

(rtmidi-dev) D:\Python\python-rtmidi\python-rtmidi>

**Comment by SpotlightKid** [comment]
Sorry, there was a typo in the branch name in my previous comment.

The full sequence of commands would be:

    git clone https://github.com/SpotlightKid/python-rtmidi
    cd python-rtmidi
    git checkout feature/59/suppress-warnings
    git submodule update --init
    pip install .

**Comment by gulaki** [comment]
**I got to this point**

(base) D:\Python\python-rtmidi>git clone https://github.com/SpotlightKid/python-rtmidi
Cloning into 'python-rtmidi'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 2990 (delta 7), reused 13 (delta 4), pack-reused 2970
Receiving objects: 100% (2990/2990), 1.57 MiB | 694.00 KiB/s, done.
Resolving deltas: 100% (1806/1806), done.

(base) D:\Python\python-rtmidi>dir
 Volume in drive D has no label.
 Volume Serial Number is D019-F367

 Directory of D:\Python\python-rtmidi

10-04-2020  16:04    <DIR>          .
10-04-2020  16:04    <DIR>          ..
10-04-2020  16:04    <DIR>          python-rtmidi
29-03-2020  21:39             1,182 test_rtmidi.py
               1 File(s)          1,182 bytes
               3 Dir(s)  60,096,667,648 bytes free

(base) D:\Python\python-rtmidi>cd python-rtmidi

(base) D:\Python\python-rtmidi\python-rtmidi>git checkout feature/59/suppress-warnings
Switched to a new branch 'feature/59/suppress-warnings'
Branch 'feature/59/suppress-warnings' set up to track remote branch 'feature/59/suppress-warnings' from 'origin'.

(base) D:\Python\python-rtmidi\python-rtmidi>git submodule update --init
Submodule 'src/rtmidi' (https://github.com/SpotlightKid/rtmidi.git) registered for path 'src/rtmidi'
Cloning into 'D:/Python/python-rtmidi/python-rtmidi/src/rtmidi'...
Submodule path 'src/rtmidi': checked out '2760817db0b5e592f30c7588e297861443515ae3'

(base) D:\Python\python-rtmidi\python-rtmidi>pip install .
Processing d:\python\python-rtmidi\python-rtmidi
Building wheels for collected packages: python-rtmidi
  Building wheel for python-rtmidi (setup.py) ... done
  Created wheel for python-rtmidi: filename=python_rtmidi-1.4.0.dev0-cp37-cp37m-win_amd64.whl size=101595 sha256=e8cd9f25e5fded91f6d13d6a9f5d84e65ca14b95e2d7affa482b7f0ad5228946
  Stored in directory: c:\users\anustuv\appdata\local\pip\cache\wheels\8d\48\de\bceafa95c5edd5733eb644164472a750561e5a62e88550f090
Successfully built python-rtmidi
Installing collected packages: python-rtmidi
Successfully installed python-rtmidi-1.4.0.dev0

(base) D:\Python\python-rtmidi\python-rtmidi>python
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import rtmidi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\python-rtmidi\python-rtmidi\rtmidi\__init__.py", line 4, in <module>
    from ._rtmidi import *  # noqa
ModuleNotFoundError: No module named 'rtmidi._rtmidi'
>>>

**Comment by gulaki** [comment]
**Trying again**

(python-rtmidi1) D:\Python\python-rtmidi>git clone https://github.com/SpotlightKid/python-rtmidi
Cloning into 'python-rtmidi'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 2990 (delta 7), reused 13 (delta 4), pack-reused 2970
Receiving objects: 100% (2990/2990), 1.57 MiB | 705.00 KiB/s, done.
Resolving deltas: 100% (1806/1806), done.

(python-rtmidi1) D:\Python\python-rtmidi>cd python-rtmidi

(python-rtmidi1) D:\Python\python-rtmidi\python-rtmidi>git checkout feature/59/suppress-warnings
Switched to a new branch 'feature/59/suppress-warnings'
Branch 'feature/59/suppress-warnings' set up to track remote branch 'feature/59/suppress-warnings' from 'origin'.

(python-rtmidi1) D:\Python\python-rtmidi\python-rtmidi>git submodule update --init
Submodule 'src/rtmidi' (https://github.com/SpotlightKid/rtmidi.git) registered for path 'src/rtmidi'
Cloning into 'D:/Python/python-rtmidi/python-rtmidi/src/rtmidi'...
Submodule path 'src/rtmidi': checked out '2760817db0b5e592f30c7588e297861443515ae3'

(python-rtmidi1) D:\Python\python-rtmidi\python-rtmidi>
(python-rtmidi1) D:\Python\python-rtmidi\python-rtmidi>pip install .
Processing d:\python\python-rtmidi\python-rtmidi
Building wheels for collected packages: python-rtmidi
  Building wheel for python-rtmidi (setup.py) ... done
  Created wheel for python-rtmidi: filename=python_rtmidi-1.4.0.dev0-cp37-cp37m-win_amd64.whl size=101601 sha256=2b0fb80743e2b55dd5b404ce3cb1301edd9e721fe28d40492d0a0c8f45317114
  Stored in directory: c:\users\anustuv\appdata\local\pip\cache\wheels\8d\48\de\bceafa95c5edd5733eb644164472a750561e5a62e88550f090
Successfully built python-rtmidi
Installing collected packages: python-rtmidi
Successfully installed python-rtmidi-1.4.0.dev0

(python-rtmidi1) D:\Python\python-rtmidi\python-rtmidi>python
Python 3.7.7 (default, Mar 23 2020, 23:19:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import rtmidi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\python-rtmidi\python-rtmidi\rtmidi\__init__.py", line 4, in <module>
    from ._rtmidi import *  # noqa
ModuleNotFoundError: No module named 'rtmidi._rtmidi'
>>>

**Comment by gulaki** [comment]
It's working! Thank you. `pip install .` is also working. i tried it a few times. i did not understand why i was getting the `rtmidi._rtmidi` error.

**Comment by gulaki** [comment]
I have another question about the usage of `rtmidi`.

    import rtmidi
    a = rtmidi.MidiOut()
    b = rtmidi.MidiOut()

This makes two instances of out port. `a.get_ports()` will return a list of available port names.

    a.open_port(0)
    b.open_port(1)

They are now two separate out ports (assuming they exist), which are both open. Is there a way to query the instances about which port number is open?

I can solve the problem by tracking which port I am opening on which instance. 

    p1, p2 = 0, 1
    a.open_port(p1)
    b.open_port(p2)

To get the port name

    a.get_ports()[p1]
    b.get_ports()[p2]

**Comment by SpotlightKid** [comment]
> `pip install .` failed

`pip install .` doesn't create the DLL file in the `rtmidi` directory in the checkout. But when you run `python` in the root of the checkout and then `import rtmidi`, it looks for and finds the package `rtmidi` in the current directory. `__init__.py` there tries to import `._rtmidi`, which isn't there, hence the `ImportError`. Solution: either change to a different directory or use `build --inplace` as you did.

> Is there a way to query the instances about which port number is open?

No. You have to keep track of this yourself. Since you already have to pass in the port number to `open_port()` this shouldn't be a problem.

Please stick to one topic per issue. Open new issues for new questions in the future.
