### ISSUE TITLE
how to consume all messages in queue

### ISSUE THREAD

**Issue by eyaler** [SpotlightKid/python-rtmidi#64]
i want to get all messages currently in the input queue, or clear the queue, or set queue_size_limit to 1 (but the argument is missing from open_midiinput). how do you suggest to do it?

**Comment by SpotlightKid** [comment]
I am sorry, but I don't understand what you are asking. What are you trying to achieve, i.e. what is your use case?

**Comment by eyaler** [comment]
whoa! thanks for super quick response. so i have a python loop which does some (slow) computation each step. and i want it to take the current state of my midi knobs as parameters. so i want to get the last message per knob and use that. otherwise i get many old messages from the queue. to overcome this, i am currently consuming all messages in an internal while loop until i get none, but i am afraid that this may get stuck in the internal loop if the user keeps moving the knobs all the time. so what i would really like is a function to pop the full current queue of messages.

**Comment by SpotlightKid** [comment]
Just attach a MIDI in callback, which records the latest message for any CC or other event you are interested in, e.g. in a class attribute, and discard all other events. In the main loop, retrieve that last value from your MIDI input handler.

Example:

```py
import time

import rtmidi
from rtmidi.midiconstants import (
    CONTROL_CHANGE,
    MODULATION,
    CHANNEL_VOLUME,
    EXPRESSION_CONTROLLER,
)


CONTROLLERS = (MODULATION, CHANNEL_VOLUME, EXPRESSION_CONTROLLER)


class MidiInHandler:
    def __init__(self, channel=1, controllers=None):
        self.ch = channel
        self.ccs = controllers or ()
        self._cur_value = {}

    def __call__(self, event, *args):
        event, delta = event
        status = event[0] & 0xF0
        ch = event[0] & 0xF

        if status == CONTROL_CHANGE and ch == self.ch - 1 and event[1] in self.ccs:
            self._cur_value[event[1]] = event[2]

    def get(self, cc, default=None):
        return self._cur_value.get(cc, default)


def main():
    midiin = rtmidi.MidiIn(rtapi=rtmidi.API_UNIX_JACK)

    # record Modulation, Volume and Expression CC events
    handler = MidiInHandler(channel=1, controllers=CONTROLLERS)
    midiin.set_callback(handler)

    try:
        with midiin.open_virtual_port():
            while True:
                for cc in CONTROLLERS:
                    print("CC #%i: %s" % (cc, handler.get(cc)))

                print("--- ")
                time.sleep(1)
    except KeyboardInterrupt:
        pass
    finally:
        del midiin

if __name__ == '__main__':
    main()
```

**Comment by eyaler** [comment]
this is awesome! thank you so much. i wonder why is this not a standard use-case... if there was a pop_all_current_queue() command i could just loop over it and update all my parameters message by message very easily to get the final updated state.

**Comment by eyaler** [comment]
i am indeed doing the get_message until None - but could i be stuck in the loop if there is constant midi changes?

**Comment by SpotlightKid** [comment]
If you need concurrency, put your MIDI I/O handling in a separate thread (or process) and use a `queue.Queue` to make MIDI events available elsewhere in your program, (e.g. its main loop). See the [midifilter example](https://github.com/SpotlightKid/python-rtmidi/blob/master/examples/midifilter/__main__.py).

**Comment by eyaler** [comment]
thanks. i am not asking about concurrency, i just want to get the lastest messages, and i worry that the "while msg is not None" loop can go on forever

**Comment by SpotlightKid** [comment]
Well, that's a general truth for handling external input. You never know, when the "last" message will have arrived, because there could always be more input coming in. Thatswhy, if you want to handle input without blocking, i.e. do something else in your program at the same time, you need concurrency. I.e. some concurrent part of you program always listens for and receives input and stores it in a queue until another part of the program gets around to retrieving it from there.

The callback mechanism in RtMidi essentially does exactly that. Putting the messages in a `queue.Queue`, like in the `midifilter` example, just further decouples parts of the program, so that not everything needs to run in the input callback.

**Comment by SpotlightKid** [comment]
Added the above example script in 2d26412c177ebbc4caef5629c685a5180eaf3c1b.

**Comment by phil123456** [comment]
no matter what I do set_callback is jjust not working, my callback is never called

**Comment by SpotlightKid** [comment]
@phil123456 Please do not re-use old issues. Open a new one and provide a minimal reproducible example, which demonstrates your problem.
