### ISSUE TITLE
Handling meta events, ie: lyrics

### ISSUE THREAD

**Issue by jmeile** [SpotlightKid/python-rtmidi#66]
Hi

I'm just wondering if it is possible to handle meta events with python rtmidi. I tried the example: midiin.py; however, sending a lyric meta event, will always result on a sytem reset message.

If I send this:
FF 05 05 79 6F 75 6E 67

Then it will be printed:
[MIDI In 1] @1592654805.196641 [255]

How can I force rtmidi to handle meta events?

Best regards
Josef

**Comment by SpotlightKid** [comment]
Meta events are only valid / possible in standard MIDI files (SMF). They can not be sent over a MIDI connection.

See here: http://www.somascape.org/midi/tech/mfile.html#events (last paragraph in this section).

`python-rtmidi` is only concerned with "on-the-wire" MIDI data, handling MIDI files is out of scope for this project.

**Comment by jmeile** [comment]
Ok, I see. I guess I will have to handle this with a custom SysEx message. I was thinking of setting up a controller with several banks and each bank should have a name. There will be a control change command to list all available banks, which will return something like:

00: My Setting 0
01: Setting 1
02: Setting 2
...

So my idea is to send afterwards a control change message with the setting index. to change to that bank.

I guess I will use one of the reserved manufacturer ids, ie: 60H. So, my message will look like

F0 60 79 6F 75 6E 67 F7

The string: "79 6F 75 6E 67" will match to: "young"

**Comment by SpotlightKid** [comment]
I suggest using the manufacturer ID `0x7D`, which is is reserved for non-commercial use (e.g. schools, research, etc.) and is not to be used on any product released to the public.

I further suggest to give your SysEx messages are future proof structure, e.g. something like

    F0 <manufacturer id> <device id> <model ID> <message type MSB> <message type LSB> data... <checksum> F7

**Comment by jmeile** [comment]
Thanks, I appreciate your suggestions and I will implement them
