### ISSUE TITLE
Can't use pip install python-rtmidi

### ISSUE THREAD

**Issue by Kliklijoker** [SpotlightKid/python-rtmidi#70]
After I issue pip install python-rtmidi I got

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting python-rtmidi
  Downloading https://files.pythonhosted.org/packages/41/d2/7c88132772864087598d975e35738c196ac9c96ef39c267c7df3eeb9cd75/python-rtmidi-1.4.3.tar.gz (248kB)
    100% |████████████████████████████████| 256kB 238kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-EX0oWL/python-rtmidi/setup.py", line 47
        print("Detected JACK version %s." % jv, file=sys.stderr)
                                                    ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-EX0oWL/python-rtmidi/

**Comment by Kliklijoker** [comment]
I found how to solve this

pip install Cython
pip3 install Cython

git clone https://github.com/SpotlightKid/python-rtmidi
cd python-rtmidi
git checkout feature/59/suppress-warnings
git submodule update --init
pip install .

**Comment by SpotlightKid** [comment]
Python 2 is not supported officially by python-rtmidi anymore. You have to run the setup.py script with Python 3.5+.

However if just pushed commit 55ef337 to the repo, which fixes this particular problem, so Python 2 may work again. But no guarantees.

Using an outdated branch is certainly **not** the correct solution.

**Comment by Kliklijoker** [comment]
Thank you for your help! SoptlightKid! If I still want use pip install python-rtmidi, how can I modify it? Now I already use pip3 install python-rtmidi and it already success.

**Comment by SpotlightKid** [comment]
If the program `pip` is the version of Pip for Python 2 on your system, then just don't use it, use `pip3` or, better, `python3 -m pip`, to ensure you are using the version of Pip for Python 3.

**Comment by SpotlightKid** [comment]
@HackXIt  @Kliklijoker 

I just released version [1.4.5](https://github.com/SpotlightKid/python-rtmidi/releases/tag/1.4.5), which should be installable with Python 2 again.
