### ISSUE TITLE
WIDIBud sysex issue

### ISSUE THREAD

**Issue by icubex** [SpotlightKid/python-rtmidi#73]
It looks like we ran into an incompatibility between WIDIBud (https://xkeyair.com/widi-bud/) and (python-)rtmidi. When sending a sysex message longer than 6 bytes total a WiDig (http://icubex.com/widig) connected via the WIDIBud doesn't receive it correctly. We can send messages correctly to the WiDig via the WIDIBud from eg. Cycling74 Max. Is (python-)rtmidi supposed to implement a BLE-MIDI protocol when sending sysex messages via a BLE-MIDI device ? Is there a flag to use/set for working with a BLE-MIDI device ?

**Comment by SpotlightKid** [comment]
python-rtmidi only implements MIDI I/O between your software and the MIDI devices provides by the MIDI API of your OS. The latter is responsible for implementing the physical protocol layer via drivers for the MIDI devices. E.g. on Linux/ALSA, the ALSA driver for USB Audio/MIDI class-compliant devices implements the actual USB communication between ALSA and the USB MIDI device.

The same would apply to Bluetooth MIDI, i.e. you MIDI backend (ALSA, JACK, CoreMIDI, etc.) needs to support BLE-MIDI devices.

Beyond these general remarks I would need to see you code and the sysex messages you are sending or trying to receive to give more specific help.

**Comment by icubex** [comment]
Thanks so much for the quick reply. Turns out there was a bug in our WiDig firmware - all fixed now. Sorry to waste your time.
