### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by betov75** [SpotlightKid/python-rtmidi#74]
Hi! I need the fastest way possible to communicate between midi and python for a MIDI translator. Is RTMidi noticeably faster alon than in Mido? How fast can I transmit midi data? In Mido, I get about 0.001 second.
Thanks for all

**Comment by SpotlightKid** [comment]
0.001 seconds is meaningless without stating what you are measuring in this period.

Besides, mido is just a wrapper around `python-rtmidi` (at least when suing the default backend), so using `python-rtmidi` will always have less layers of function/method calls. But the difference shouldn't really be noticeable.

If you are talking to a hardware MIDI-Interface, the speed is likely limited by either the USB throughput or the standard speed of DIN-MIDI (31250 baud, which is roughly 1 ms per MIDI message). Another factor is latency. This depends on the hardware latency of you interface, or the USB poll interval of the USB host, the size of the buffers of the MIDI backend of your OS and the poll interval in your code (if you use polling). So it's impossible to determine this exactly without knowing the exact system setup.

**Comment by SpotlightKid** [comment]
Closing this due to no further feedback.
