### ISSUE TITLE
rtmidi_python.pyx : expected bytes, str found

### ISSUE THREAD

**Issue by louisJ20** [SpotlightKid/python-rtmidi#77]
hello, i am working on a project with rtmidi.  I made my program on macOS with a MIDI device.  however I have to run it on a Raspberry pi4.  When I run my program on the Raspberry, this error message appears (see photo).  would you have a solution?  Thank you.

![image](https://user-images.githubusercontent.com/56971289/107154676-96ad6180-6974-11eb-8209-679adbb8202f.jpeg)

**Comment by SpotlightKid** [comment]
`rtmidi_python-pyx` is not from this package. You have a different package installed.

**Comment by louisJ20** [comment]
> `rtmidi_python-pyx` is not from this package. You have a different package installed.

I have this error on the Raspberry only

**Comment by SpotlightKid** [comment]
That's not relevant. You are *not* using `python-rtmidi`.

Please make sure that you installed it with `pip install python-rtmidi` (not `pip install rtmidi` or any other package).

**Comment by louisJ20** [comment]
> That's not relevant. You are _not_ using `python-rtmidi`.
> 
> Please make sure that you installed it with `pip install python-rtmidi` (not `pip install rtmidi_python` or `pip install rtmidi` or any other package).

Yes i did `pip install python-rtmidi`
![IMG_5702](https://user-images.githubusercontent.com/56971289/107156026-1ee33500-697c-11eb-9450-8fdb45522f47.jpeg)
 but when i ran my program an error appears. On my mac there is ont this error.

![IMG_5703](https://user-images.githubusercontent.com/56971289/107156015-17239080-697c-11eb-97bf-239d031cd065.jpeg)

**Comment by louisJ20** [comment]
![IMG_5703](https://user-images.githubusercontent.com/56971289/107156036-2e627e00-697c-11eb-9c32-9510cfe5380b.jpeg)
![IMG_5702](https://user-images.githubusercontent.com/56971289/107156037-30c4d800-697c-11eb-9057-4d54610f3a53.jpeg)

**Comment by louisJ20** [comment]
I did this command but when I run the command python myfile.py the error not module named rtmidi is found. I wrote import python_rtmidi in my file

**Comment by SpotlightKid** [comment]
Please try the simple example from the readme *exactly*:

https://github.com/SpotlightKid/python-rtmidi#usage-example

Save it to a file (e.g. `testrtmidi.py`) and run it with `python3 testrtmidi.py`.

If that gives an error, please copy-and paste *all output* here (no screenshot please).

**Comment by louisJ20** [comment]
This error appears : 

pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    main()
  File "main.py", line 21, in main
    message, delta_time = midi_in.get_message()
TypeError: cannot unpack non-iterable NoneType object

On my mac, the program is waiting for me to press a key on my MIDI device. However on the raspberry, it closes immediately and this error appears. I have executed the python3 command.

> Please try the simple example from the readme _exactly_:
> 
> https://github.com/SpotlightKid/python-rtmidi#usage-example
> 
> Save it to a file (e.g. `testrtmidi.py`) and run it with `python3 testrtmidi.py`.
> 
> If that gives an error, please copy-and paste _all output_ here (no screenshot please).

**Comment by SpotlightKid** [comment]
The output you posted is obviously not from the example I asked you to run.

Sorry, if you ignore my instructions, I am not able to help you and will ignore you as well.

**Comment by louisJ20** [comment]
> The output you posted is obviously not from the example I asked you to run.
> 
> 
> 
> Sorry, if you ignore my instructions, I am not able to help you and will ignore you as well.

Sorry, there is zero error with the example.

**Comment by SpotlightKid** [comment]
So that means that `python-rtmidi` is working but the other code (`main.py`) is **not using** `python-rtmidi`, but probably something that comes with pygame. I can't help with that. Please use their support channels or a general Python forum/mailing list/chat.

**Comment by louisJ20** [comment]
> So that means that `python-rtmidi` is working but the other code (`main.py`) is **not using** `python-rtmidi`, but probably something that comes with pygame. I can't help with that. Please use their support channels or a general Python forum/mailing list/chat.

only with rtmidi, MIDI inputs do not display messages.  Do you think there is any configuration to do on the raspberry?
