### ISSUE TITLE
Cannot open certain port names on Windows

### ISSUE THREAD

**Issue by crankedguy** [SpotlightKid/python-rtmidi#78]
Hi,

you cannot open certain port names on Windows. I think it is because the port may contain certain characters as the communication with other apps is working without any problems. 
I discovered the error through mido, which uses the port names itself but then tracked it down python-rtmidi which uses the port number where it is also not possible.

This works 
```
import rtmidi

midiin = rtmidi.MidiIn()

avail_ports = midiin.get_ports()

for port in avail_ports:
    print(port)

midiin.open_port(1)

while True:
    if midiin.get_message():
        print("Message")
```

But this does not, which tries to open the "MIDIIN2 (Ableton Push 2) 2" port
midiin.open_port(2)

D:\Development\Push2\push2-captureone>python try_rtmidi.py
Bome MIDI Translator 1 0
Ableton Push 2 1
MIDIIN2 (Ableton Push 2) 2
Traceback (most recent call last):
  File "D:\Development\Push2\push2-captureone\try_rtmidi.py", line 10, in <module>
    midiin.open_port(2)
  File "src/_rtmidi.pyx", line 586, in rtmidi._rtmidi.MidiBase.open_port
  File "src/_rtmidi.pyx", line 220, in rtmidi._rtmidi._cb_error_func
  File "src/_rtmidi.pyx", line 408, in rtmidi._rtmidi._default_error_handler
rtmidi._rtmidi.SystemError: MidiInWinMM::openPort: error creating Windows MM MIDI input port.

**Comment by SpotlightKid** [comment]
Can you use the "MIDIIN2 (Ableton Push 2) 2" in other software, e.g. midi-ox?

**Comment by crankedguy** [comment]
Yes without any issues, I use it with BOME Midi Translator pro for instance

**Comment by SpotlightKid** [comment]
Would you be able to compile the example programs from RtMidi (the underlying C++ library) and test the same port with the `qmidiin` program?

https://github.com/SpotlightKid/rtmidi/blob/2760817db0b5e592f30c7588e297861443515ae3/tests/qmidiin.cpp

I never tried compiling these on windows, though.

**Comment by crankedguy** [comment]
The thing is I develop(ed) software since 1991, and I managed it perfectly in all these years to develop anything in Windows :D :D  
Every time I try to compile something there it turns out into a complete disaster (Visual Studio project 125 years old and not to be upgradeable, general OS issues etc. etc.)
I just use Windows because a lot of SW I use nowadays needs it.
So if you might know someone who is used to that sh.t and can provide me a binary quicker than I am able to I am happy to test it out for you any time.

**Comment by SpotlightKid** [comment]
I don't actually have a Windows installation, the binary wheels for `python-rtmidi` for Windows are produced on the AppVeyor CI. So I can't help with RtMidi example program binaries.

Without testing, whether opening the "MIDIIN2 (Ableton Push 2) 2" port also fails with these, it will be very hard to get to the bottom of this. The error occurs when `python-rtmidi` calls the underlying C++ library and within that C++ code. So it is very unlikely an error in the `python-rtmidi` wrapper code.

Maybe these (admittedly old) instructions will help?

https://beatinginfinity.blogspot.com/2013/05/use-rtmidi-in-windows-in-microsoft.html

Apart from that, I can only suggest to open a ticket in the RtMidi Github project:

https://github.com/thestk/rtmidi/issues

**Comment by crankedguy** [comment]
Ok thanks so far. I will see if I get this managed somehow although there are so much issues normally between the versions of this damn Microsoft product I don't know if it will work out.

Opening a ticket in RTMidi might help more actually, as I can clearly confirm that the port is working and accessible.

**Comment by SpotlightKid** [comment]
It may help to point out, the error happens exactly here in `RtMidi.cpp`:

https://github.com/thestk/rtmidi/blob/84d130bf22d878ff1b0e224346e2e0f9e3ba8099/RtMidi.cpp#L2604

**Comment by SpotlightKid** [comment]
Ok, [turns out](https://github.com/thestk/rtmidi/issues/234) the port was already opened by another application (Bome MID Translator). WinMM only allows one application to access a port at a time.
