### ISSUE TITLE
Cannot set API of MidiOut to API_RTMIDI_DUMMY

### ISSUE THREAD

**Issue by obeezzy** [SpotlightKid/python-rtmidi#82]
I'm trying to set up CI using GitHub actions, but the server complains about a missing device:
`ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory`

To circumvent this issue, I decided to use `rtmidi.API_RTMIDI_DUMMY` instead, however, I seem to be getting some weird results:
```
from rtmidi import MidiOut, API_RTMIDI_DUMMY

print(API_LINUX_ALSA)  # Prints 2
print(API_RTMIDI_DUMMY)  # Prints 5
midiout = MidiOut(API_RTMIDI_DUMMY)
print(midiout.get_current_api())  #  Prints 2
```

Testing on my computer yields `RtMidiOut: no compiled support for specified API argument!`.

What is the proper way to use `rtmidi.API_RTMIDI_DUMMY`? Am I doing something wrong?

**Comment by SpotlightKid** [comment]
The `RTMIDI_DUMMY` API is a fallback, which is only compiled in when none of the other APIs is defined or available at *compilation time*:

https://github.com/SpotlightKid/rtmidi/blob/2760817db0b5e592f30c7588e297861443515ae3/RtMidi.cpp#L60

The pre-processor defines to select the backend APIs, which are compiled in are set up in `setup.py`:

https://github.com/SpotlightKid/python-rtmidi/blob/25b074dcc920cbb3289756d89ee9abcc4be7dc29/setup.py#L149

So you would need to compile a special version for your CI by passing `--no-alsa`  and `--no-jack` to `python setup.py build_ext` (in theory, untested).

**Comment by obeezzy** [comment]
@SpotlightKid , thanks for your response. I decided to "mock" the class instead.
