### ISSUE TITLE
MIDI Input callback delta - how to get timestamp of first event?

### ISSUE THREAD

**Issue by RogerLevy** [SpotlightKid/python-rtmidi#83]
I had assumed that the delta of the first event would be the relative time since the input port was opened, but I was somewhat surprised to find that it's actually zero.  This makes it difficult to write an accurate MIDI sequencer as I have no way of knowing exactly when the first event came in.  I tried adding a best guess but it's not a good solution as the timing for the resulting first event and all subsequent events is different every time.  

Here's the code for the workaround:
```
    if delta == 0:
        delta = time.time() - (35/1000) - start_time
```

**Comment by SpotlightKid** [comment]
Hi there, thanks for the report.

However, `python-rtmidi` is only a wrapper around [RtMidi](http://www.music.mcgill.ca/~gary/rtmidi/index.html), and only passes on the event from the C++ library to the Python layer.

I suggest opening and issue here:

https://github.com/thestk/rtmidi/issues

**Comment by SpotlightKid** [comment]
Upstream issue: https://github.com/thestk/rtmidi/issues/243
