### ISSUE TITLE
Python3 - RtMidi - input callback not working

### ISSUE THREAD

**Issue by phil123456** [SpotlightKid/python-rtmidi#85]
Hello

I just try to read midi inputs from a callback

if I use .get_message, **I get midi messages but midiclocks never come in**

**so I try to use an input callback**

*the callback is NEVER CALLED*

```
midiInAlsa = rtmidi.MidiIn(rtapi=rtmidi.API_LINUX_ALSA)
midiInAlsa.set_callback(self.rtMidiInputCallback)
midiInAlsa.set_error_callback(self.rtMidiErrorCallback)
midiInAlsa.ignore_types(sysex=False, timing=False, active_sense=False)
self.inMidiAlsaPort, port_name = open_midiport("some midi port",type_="input",api=rtmidi.API_LINUX_ALSA,interactive=False)
```

later in my class, the callbacks are defined

```
def rtMidiInputCallback(self,message,data):
    print("rtMidiInputCallback")

def rtMidiErrorCallback(self,type,message:str,data):
    print("rtMidiErrorCallback")
```

can you help me with this issue?

thanks for your help

**Comment by SpotlightKid** [comment]
Please provide *complete*, runnable code. Otherwise I can't reproduce your problem reliably or determine whether the problem lies with python-rtmidi or some error in your code.

**Comment by SpotlightKid** [comment]
Also, please try the example script [`examples/advanced/midiclock.py`](https://github.com/SpotlightKid/python-rtmidi/blob/master/examples/advanced/midiclock.py) and send MIDI clock messages to its input and report whether that works for you.

**Comment by phil123456** [comment]
```
import rtmidi
from rtmidi.midiutil import open_midioutput,open_midiport
from rtmidi.midiconstants import NOTE_OFF, NOTE_ON

class SomeClass:

    def init(self):
        midiInAlsa = rtmidi.MidiIn(rtapi=rtmidi.API_LINUX_ALSA)
        midiInAlsa.set_callback(self.rtMidiInputCallback)
        midiInAlsa.set_error_callback(self.rtMidiErrorCallback)
        midiInAlsa.ignore_types(sysex=False, timing=False, active_sense=False)
        self.inMidiAlsaPort, port_name = open_midiport("f_midi:f_midi 16:0",type_="input",api=rtmidi.API_LINUX_ALSA,interactive=False)

    def run(self):
        while True:
            print ("wait")
    
    def rtMidiInputCallback(self,message,data):
        print("rtMidiInputCallback")

    def rtMidiErrorCallback(self,type,message:str,data):
        print("rtMidiErrorCallback")

c=SomeClass()
c.init()
c.run()



```

**Comment by phil123456** [comment]
I'll check your script

to be sure my raspberry pi was receivind midi data & clock, I use qmidiroute, which shows data

https://i.postimg.cc/JzSHJQqV/Untitled.png

**Comment by phil123456** [comment]
I dont get it, in your script, the arg[0] is used as a bpm for the midireceiver class and the port id (I guess) that will be open

```
def main(args=None):
    clock = MIDIClockReceiver(float(args[0]) if args else None)

    m_in, port_name = open_midiinput(args[0] if args else None)
```

**Comment by SpotlightKid** [comment]
You are creating a `rtmidi.MidiIn` instance on the first line of the `init` method, but you are not saving it to a an instance attribute, so it will get deleted after the method exits. Then you create another `rtmidi.MiniIn` instance via the `open_midiport` function, but you do not attach the callback function to that. See the `midiclock.py` example on how to do it properly.

**Comment by phil123456** [comment]
ok it works apparently

I'll try to figure what's wrong in my code

```
Waiting for clock sync...
1.00 bpm (no sync)
1.00 bpm (no sync)
1.00 bpm (no sync)
1.00 bpm (no sync)
1.00 bpm (no sync)
1.00 bpm (no sync)
1.00 bpm (no sync)
1.00 bpm (no sync)
1.00 bpm (no sync)
START/CONTINUE received.
119.86 bpm
120.07 bpm
120.16 bpm
120.28 bpm
119.85 bpm
119.80 bpm
120.09 bpm
120.00 bpm
120.09 bpm
119.85 bpm
120.07 bpm
STOP received.
```

**Comment by phil123456** [comment]
> 
> 
> You are creating a `rtmidi.MidiIn` instance on the first line of the `init` method, but you are not saving it to a an instance attribute, so it will get deleted after the method exits. Then you create another `rtmidi.MiniIn` instance via the `open_midiport` function, but you do not attach the callback function to that. See the `midiclock.py` example on how to do it properly.

glad you were there to help...git issues ROI are like <1% :-)

**Comment by SpotlightKid** [comment]
> git issues ROI are like <1% :-)

If you make it easy for the developer to reproduce your problem, e.g. by providing minimal, complete, reproducible example from the start, you might have better luck.

And remember that Open Source developers in general work on their projects for free in their own private time, so it's helpful to expect nothing and be grateful for anything you receive. For example by saying thank you.

**Comment by SpotlightKid** [comment]
> the arg[0] is used as a bpm for the midireceiver class and the port id (I guess) that will be open 

That's an error an will be fixed.

**Comment by phil123456** [comment]
I provide a lot of info generaly, sometimes you even have to fill forms

I certainly understand devs are working on heir own project on teir free time

I am a dev too and Ia m gratefull...maybe I expressed it the wrong way

**Comment by SpotlightKid** [comment]
> I am a dev too and I am gratefull...maybe I expressed it the wrong way

All good.
