### ISSUE TITLE
Crashes in port enumeration on MacOS

### ISSUE THREAD

**Issue by Noir-** [SpotlightKid/python-rtmidi#89]
There is (was) a bug in rtmidi which leads to crashes when enumerating ports on MacOS: https://github.com/thestk/rtmidi/issues/155

Luckily the pull request which mitigates this was just merged: https://github.com/thestk/rtmidi/pull/220

Can you please have a look into this?

**Comment by SpotlightKid** [comment]
I'll look into it as soon as I have time.

**Comment by SpotlightKid** [comment]
Release 1.4.9 includes this upstream PR.
