### ISSUE TITLE
Wheel for python 3.9 Windows please _/\_

### ISSUE THREAD

**Issue by nir** [SpotlightKid/python-rtmidi#90]

**Comment by SpotlightKid** [comment]
Builds for Python 3.9 are supported in theory. Unfortunately, AppVeyor, the build service used for Windows builds [has an error](https://ci.appveyor.com/project/SpotlightKid/python-rtmidi/builds/38863906/job/ofir4up9r0reabp1) in its build environment for Python 3.9, so the binary wheels for Windows /  Python 3.9 didn't get build for the last release.

I'll do bugfix release as soon as I find a workaround.

**Comment by SpotlightKid** [comment]
Release 1.4.9 now has a 64-bit Python.9 binary wheel for Windows again as well.
