### ISSUE TITLE
Python refuse to use python-rtmidi 

### ISSUE THREAD

**Issue by Manaberry** [SpotlightKid/python-rtmidi#91]
Hi,

I've installed python 3.7.0 on my Raspberry Pi 4 (Windows 10 ARM) and I've proceeded to install python-rtmidi without any issue. However, when I try to use OSC, I've got an error that python-rtmidi is not installed. 

Here is the post from OSC Community with screenshots to understand the problem I'm facing: https://openstagecontrol.discourse.group/t/python-rtmidi-not-found-windows-arm/1477/8

I have no clue how to fix this. Can you guys help me please?

Thanks

**Comment by SpotlightKid** [comment]
Can you post the full output of:

    python --version
    python -c 'import rtmidi;print(rtmidi.__version__, rtmidi._rtmidi.__file__)'

`python` here should refer to the same version of the Python interpreter you are running open stage control with.

And please copy-and-paste the output as text, not as a screenshot.

**Comment by Manaberry** [comment]
Okay, with your command lines I was able to make further research (thanks to you, those precious error message are so helpful).
vc_redist.x86.exe was the missing part. By installing it, I now got

`1.4.9 C:\Users\Manaberry\AppData\Local\Programs\Python\Python39\lib\site-packages\rtmidi\_rtmidi.cp39-win_amd64.pyd`

**Comment by SpotlightKid** [comment]
That looks good. Does Open Stage Control recognize the python-rtmidi installation now?

**Comment by Manaberry** [comment]
> That looks good. Does Open Stage Control recognize the python-rtmidi installation now?

It does. I just have to figure out why it doesn't show the port I've created with rtpmidi now haha.
Thanks for your help! You saved my ass on this tough one!

**Comment by SpotlightKid** [comment]
I don't provide pre-compiled binary wheels for Windows ARM, so you need a compiler on the target system.

**Comment by Manaberry** [comment]
I've never done that before but I guess it's time to learn! Thanks

**Comment by SpotlightKid** [comment]
If you compiled python-rtmidi yourself (possibly via `pip install`), make sure you verify your installation: https://spotlightkid.github.io/python-rtmidi/install-windows.html#verify-your-installation

**Comment by Manaberry** [comment]
I've compiled on my side. However, nothing has changed.
I connected a USB Midi keyboard and this one as well is not recognized (even with another software). So I assume this is on Windows' end.

**Comment by SpotlightKid** [comment]
Did you do the verification steps I linked above? Does `rtmidi.API_WINDOWS_MM in rtmidi.get_compiled_api()` return `True`?

**Comment by SpotlightKid** [comment]
Closing due to no further feedback.
