### ISSUE TITLE
Suggestion to allow multiple ports per client

### ISSUE THREAD

**Issue by to7m** [SpotlightKid/python-rtmidi#95]
Hello, I'm hoping to make a MIDI client with this package which has multiple ports, but as far as I see there is no way to have more than 1 port per client.

In case I've overlooked something and there's already a way, I'm using Alsa MIDI on Arch Linux.

All the best, and thanks for the very useful package (:

**Comment by SpotlightKid** [comment]
You need one `MidiIn` resp. `MidiOut` instance per input resp. output port. Nothing prevents you from creating several instances of these for different ports.

**Comment by to7m** [comment]
Any chance of an example of how to do this with the same client? My code always creates multiple clients (1 port each), even with the same client name passed.

**Comment by SpotlightKid** [comment]
Oh, I didn't quite understand you question at first. The ALSA backend uses `snd_seq_open` for every `MidiIn` or `MidiOut` instance (see [here](https://github.com/thestk/rtmidi/blob/master/RtMidi.cpp#L2174) and [here](https://github.com/thestk/rtmidi/blob/master/RtMidi.cpp#L1816)).

This is just how RtMidi works. It abstract different backend MID frameworks and concepts, providing a cross-platform API but you loose some control over details .

**Comment by to7m** [comment]
Ah okay. Thanks for the clarification!
