### ISSUE TITLE
RtMidiIn set_callback doesn't recognise callable

### ISSUE THREAD

**Issue by to7m** [SpotlightKid/python-rtmidi#97]
Hello,

I'm having some trouble figuring out why the `set_callback` method of a `MidiIn` object is giving me this error. I'm passing it a callable (in this case, the `put` method of a `multiprocessing.Queue`), but it looks like it thinks it's getting an int.

```
TypeError: 'int' object is not callable
Exception ignored in: 'rtmidi._rtmidi._cb_func'
TypeError: 'int' object is not callable
```

I've been trying to make a reproducible example, but it only happens occasionally in a big project. Insight as to how this error could be happening might save me a few reboots and help me reproduce the problem.

Thanks!
Tom

**Comment by SpotlightKid** [comment]
Thanks for your report, but without a full traceback, I have not much of a chance of analyzing what happened. Even better would be to see your _actual_ source code, at least the part, where you register the callback. Please note that the callback must have the correct signature, as described in the docs.

**Comment by to7m** [comment]
Any advice on how to get a full traceback? I don't know any cython so the code looks a bit alien to me. It might be useful if I could get it to print the object it thinks is an int (or occasionally NoneType), or somehow stop it ignoring the Exception.

Am I right in thinking a signature means the args the callback takes? If so, the callback `multiprocessing.Queue().put` handles the args fine usually.

I've tried to make a reproducible examples, but none of them so far print that output. I'll keep trying, but in the meantime, here is some additional info:

The whole code is [here](https://gitlab.com/to7m/to7m_midi_handler), with the main script at `./bin/to7m-midi-handler`. The callback is assigned in `./src/to7m_midi_handler/io_/python_rtmidi_wrappers.py` in line 24.

The error message gets printed when a message is sent from a real controller to the relevant port. Most times when I run the program, the error doesn't happen, and won't happen for as long as it runs, but if I kill it and restart it enough times, eventually the error occurs, or ALSA breaks.

**Comment by to7m** [comment]
The callback assigning code snippet from `./src/to7m_midi_handler/io_/python_rtmidi_wrappers.py`:

```
port = MidiIn(name=INTERNAL_CLIENT_NAME)
port.open_virtual_port(name)
port.ignore_types(False)

port_queue = Queue()
port.set_callback(port_queue.put, data=True)
```

**Comment by SpotlightKid** [comment]
> Any advice on how to get a full traceback?

You could insert a print() statement before line 212 in `_rtmidi.pyx` to check which type `func` has. It should be the `port_queue.put` bound method, which you passed to `set_callback`, but I haven't looked through your whole code.

**Comment by to7m** [comment]
I inserted this line at 212: `print(f"{func}, {type(func)}, {id(func)}, {data}")`

Output from when it works: `<bound method Queue.put of <multiprocessing.queues.Queue object at 0x7fb6ab1422e0>>, <class 'method'>, 140422530298624, True`
Output from when it fails: `140, <class 'int'>, 140010163579600, 143` (the ints change when I restart the program)

So, I was thinking it might be a problem with `Queue`, but it looks like the `data` argument also changes (from True to a random int).

**Comment by SpotlightKid** [comment]
Looks like a memory issue. Can you make sure that the callback runs in the same thread/process where the `MidiIn` instance was created?

**Comment by to7m** [comment]
I made a change that seems to be working.

Old:
```
port_queue = Queue()
port.set_callback(queue_put, data=True)
```
New:
```
port_queue = Queue()
def queue_put(*x):
    port_queue.put(*x)
port.set_callback(queue_put, data=True)
```

This also fixes another problem I was having. I guess this means it was either a problem in `Queue` all along, or I just misapplied multiprocessing. Thanks for the help!

Any insight into what makes the difference? Could it be that `Queue.put` sometimes runs in a different process than that which the `Queue` was created in?

**Comment by SpotlightKid** [comment]
> Could it be that Queue.put sometimes runs in a different process than that which the Queue was created in?

Yes, that wouldn't work. The `set_callback` stores a reference to the Python object representing the Python callback function or bound-method. That is, of course, not valid in another process.

**Comment by to7m** [comment]
Okay I think I'm starting to understand what I did wrong. Everything's working fine now so I'll close this. Thanks again!

**Comment by to7m** [comment]
Just an irrelevant side-note...

Using a similar closure approach, this works as long as I save some scoped variables in a global list to stop their `__del__` methods being called (messy I know). If I only save the callback closure this way and none of the others, then the inserted print line suggests that the callback might now be a tuple that contains a self-referencing tuple:
`((((((((((((((((((...), True), True), True), True), True), True), True), True), True), True), True), True), True), None), None), [(...), (...), [...]]), 0), <class 'tuple'>, 139814040658688, True`
Just thought that was cool.
